apiVersion: v1
kind: ConfigMap
metadata:
  name: iioflux
  namespace: iioflux
data:
  sensors.yaml: |-
    hosts:
    - name: neon
      remote: "neon.thuis.efgh.nl:30431"
      devices:
      - name: bme280
        match:
          name: bme280
