apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: dex
  namespace: dex
spec:
  interval: 5m
  chart:
    spec:
      chart: dex
      version: 0.19.1
      sourceRef:
        kind: HelmRepository
        name: dex
        namespace: flux-system
  values:
    config:
      connectors:
      - type: google
        id: google
        name: Google
        config:
          clientID: $GOOGLE_CLIENT_ID
          clientSecret: $GOOGLE_CLIENT_SECRET
          redirectURI: https://dex.9ka.nl/callback
          hostedDomains:
          - kippendief.biz
      issuer: https://dex.9ka.nl
      staticClients:
      - idEnv: CLIENT_OAUTH2_PROXY_ID
        name: OAuth2 Proxy
        redirectURIs:
        - https://alertmanager.9ka.nl/oauth2/callback
        - https://justnimbus.9ka.nl/oauth2/callback
        - https://laadpaal.9ka.nl/oauth2/callback
        - https://netbox.9ka.nl/oauth2/callback
        - https://prometheus.9ka.nl/oauth2/callback
        - https://sabnzbd.9ka.nl/oauth2/callback
        - https://sonarr.9ka.nl/oauth2/callback
        - https://transmission.9ka.nl/oauth2/callback
        secretEnv: CLIENT_OAUTH2_PROXY_SECRET
      - idEnv: CLIENT_GRAFANA_ID
        redirectURIs:
        - https://grafana.9ka.nl/login/generic_oauth
        name: Grafana
        secretEnv: CLIENT_GRAFANA_SECRET
      storage:
        type: kubernetes
        config:
          inCluster: true
      web:
        http: 0.0.0.0:5556
    env:
      KUBERNETES_POD_NAMESPACE: dex
    envFrom:
    - secretRef:
        name: secret-env
    ingress:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt
      className: nginx
      hosts:
      - host: dex.9ka.nl
        paths:
        - path: /
          pathType: ImplementationSpecific
      tls:
      - secretName: dex-tls
        hosts:
        - dex.9ka.nl
    resources:
      requests:
        cpu: 100m
        memory: 32Mi
      limits:
        cpu: 100m
        memory: 64Mi
