apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: monitoring-crd
  namespace: flux-system
spec:
  interval: 10m
  path: "./clusters/9ka/monitoring/crd/"
  prune: true
  timeout: 1m
  sourceRef:
    kind: GitRepository
    name: flux-system
