apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: prowlarr
  namespace: prowlarr
  labels:
    app.kubernetes.io/name: prowlarr
    app.kubernetes.io/version: 1.6.3.36098
spec:
  serviceName: prowlarr
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: prowlarr
  template:
    metadata:
      labels:
        app.kubernetes.io/name: prowlarr
    spec:
      containers:
      - name: prowlarr
        image: ghcr.io/hotio/prowlarr:release
        env:
        - name: TZ
          value: Europe/Amsterdam
        - name: PUID
          value: '1000'
        - name: PGID
          value: '1000'
        - name: UMASK
          value: '002'
        ports:
        - containerPort: 9696
          name: http
        volumeMounts:
        - name: config
          mountPath: /config
        startupProbe:
          httpGet:
            port: http
          timeoutSeconds: 5
          failureThreshold: 120
        readinessProbe:
          httpGet:
            port: http
          timeoutSeconds: 5
          failureThreshold: 10
        livenessProbe:
          httpGet:
            port: http
          failureThreshold: 3
  volumeClaimTemplates:
  - metadata:
      name: config
    spec:
      accessModes: [ ReadWriteOnce ]
      resources:
        requests:
          storage: 1Gi
