apiVersion: v1
kind: Service
metadata:
  name: netbox-kea-pve
  labels:
    app.kubernetes.io/name: netbox-kea
    app.kubernetes.io/instance: netbox-kea-pve
  namespace: kea
spec:
  selector:
    app.kubernetes.io/name: netbox-kea
    app.kubernetes.io/instance: netbox-kea-pve
