apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: influxdb2
  namespace: influxdb
spec:
  interval: 5m
  chart:
    spec:
      chart: influxdb2
      version: 2.0.8
      sourceRef:
        kind: HelmRepository
        name: influxdata
        namespace: flux-system
  values:
    persistence:
      enabled: true
    resources:
      requests:
        cpu: 250m
        memory: 2Gi
      limits:
        cpu: 4000m
        memory: 4Gi
