apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: influxdb2
  namespace: influxdb
spec:
  interval: 5m
  chart:
    spec:
      chart: influxdb2
      version: 2.1.2
      sourceRef:
        kind: HelmRepository
        name: influxdata
  values:
    image:
      tag: 2.7.10-alpine # repo=docker.io/influxdb
    startupProbe:
      enabled: true
      periodSeconds: 5
      failureThreshold: 24
    persistence:
      enabled: true
    resources:
      requests:
        cpu: 250m
        memory: 2Gi
      limits:
        cpu: 4000m
        memory: 4Gi
    ingress:
      enabled: true
      ingressClassName: nginx
      hostname: influx.9ka.nl
      secretName: influxdb2-tls
      tls: true
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt
