apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: influxdb2
spec:
  interval: 5m
  chart:
    spec:
      chart: influxdb2
      version: 2.1.2
      sourceRef:
        kind: HelmRepository
        name: influxdata
  values:
    image:
      tag: 2.7.12-alpine # repo=docker.io/influxdb
    startupProbe:
      enabled: true
      periodSeconds: 5
      failureThreshold: 24
    persistence:
      enabled: true
      storageClass: proxmox-zfs-nvme
    resources:
      requests:
        cpu: 250m
        memory: 2Gi
      limits:
        cpu: 4000m
        memory: 4Gi
    ingress:
      enabled: true
      className: cilium
      hostname: influx.9ka.nl
      secretName: influxdb2-tls
      annotations:
        external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
        external-dns.alpha.kubernetes.io/hostname: influx.9ka.nl
        external-dns.alpha.kubernetes.io/target: 431113a6-4cf3-4a66-9750-17113ae2e689.cfargotunnel.com
