apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: influxdb2
  namespace: influxdb
spec:
  interval: 5m
  chart:
    spec:
      chart: influxdb2
      version: 2.1.2
      sourceRef:
        kind: HelmRepository
        name: influxdata
  values:
    image:
      tag: 2.7.12-alpine # repo=docker.io/influxdb
    startupProbe:
      enabled: true
      periodSeconds: 5
      failureThreshold: 24
    persistence:
      enabled: true
      storageClass: proxmox-zfs-nvme
    resources:
      requests:
        cpu: 250m
        memory: 2Gi
      limits:
        cpu: 4000m
        memory: 4Gi
    ingress:
      enabled: true
      ingressClassName: cilium
      hostname: influx.9ka.nl
      secretName: influxdb2-tls
      tls: true
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: topology.kubernetes.io/region
              operator: In
              values:
              - thuis-svc
    tolerations:
    - operator: Equal
      key: efgh.nl/location
      value: zolder
      effect: NoSchedule
