apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: influxdb
  namespace: influxdb
spec:
  interval: 5m
  chart:
    spec:
      chart: influxdb
      version: 4.10.2
      sourceRef:
        kind: HelmRepository
        name: influxdata
        namespace: flux-system
  values:
    config:
      http:
        auth-enabled: true
    setDefaultUser:
      enabled: true
#    ingress:
#      annotations:
#        cert-manager.io/cluster-issuer: letsencrypt
#      className: nginx
#      enabled: true
#      hostname: influxdb.9ka.nl
#      tls: true
#      secretName: influxdb-tls
    persistence:
      enabled: true
    resources:
      requests:
        cpu: 150m
        memory: 350Mi
      limits:
        cpu: 1000m
        memory: 1Gi
