---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-datasource
  labels:
    grafana_datasource: "1"
data:
  prometheus.yaml: |-
    apiVersion: 1
    datasources:
    - name: Prometheus
      type: prometheus
      url: http://prometheus-operated.monitoring:9090/
      access: proxy
