---
apiVersion: v1
kind: ConfigMap
metadata:
  name: sunmoon-datasource
  labels:
    grafana_datasource: "1"
data:
  sunmoon.yaml: |-
    apiVersion: 1
    datasources:
    - name: 'Sun and Moon'
      type: fetzerch-sunandmoon-datasource
      access: proxy
      editable: false
      jsonData:
        latitude: 52.199349
        longitude: 6.853604
...
