apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: external-dns
  namespace: ingress
spec:
  interval: 5m
  chart:
    spec:
      chart: external-dns
      version: 1.18.0
      sourceRef:
        kind: HelmRepository
        name: external-dns
  values:
    sources:
    - ingress
    policy: sync
    interval: 5m
    triggerLoopOnEvent: true
    provider:
      name: cloudflare
    env:
    - name: CF_API_TOKEN
      valueFrom:
        secretKeyRef:
          name: cloudflare-secrets
          key: apiKey
    tolerations:
    - key: efgh.nl/location
      operator: Equal
      value: zolder
      effect: NoSchedule
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: topology.kubernetes.io/region
              operator: In
              values:
              - thuis-svc
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 1000m
        memory: 256Mi
