apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cilium
  namespace: cilium
spec:
  interval: 5m
  chart:
    spec:
      chart: cilium
      version: 1.16.3
      sourceRef:
        kind: HelmRepository
        name: cilium
        namespace: flux-system
  values:
    upgradeCompatibility: "1.12"
    hubble:
      relay:
        enabled: true
      metrics:
        enabled:
        - drop
        serviceMonitor:
          enabled: true
    kubeProxyReplacement: true
    k8sServiceHost: 9ka.nl
    k8sServicePort: 6443
    prometheus:
      enabled: true
      serviceMonitor:
        enabled: true
    operator:
      prometheus:
        enabled: true
        serviceMonitor:
          enabled: true
    securityContext:
      privileged: true
