apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cilium
  namespace: cilium
spec:
  interval: 5m
  chart:
    spec:
      chart: cilium
      version: 1.18.1
      sourceRef:
        kind: HelmRepository
        name: cilium
  values:
    upgradeCompatibility: "1.12"
    hubble:
      relay:
        enabled: true
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
              - matchExpressions:
                - key: topology.kubernetes.io/region
                  operator: In
                  values:
                  - thuis-svc
        tolerations:
        - operator: Equal
          key: efgh.nl/location
          value: zolder
          effect: NoSchedule
      metrics:
        enabled:
        - drop
        serviceMonitor:
          enabled: true
    kubeProxyReplacement: true
    k8sServiceHost: 9ka.nl
    k8sServicePort: 6443
    ingressController:
      enabled: true
      loadbalancerMode: shared
      service:
        type: ClusterIP
        externalTrafficPolicy: ~
    prometheus:
      enabled: true
      serviceMonitor:
        enabled: true
    operator:
      prometheus:
        enabled: true
        serviceMonitor:
          enabled: true
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: topology.kubernetes.io/region
                operator: In
                values:
                - thuis-svc
      tolerations:
      - operator: Equal
        key: efgh.nl/location
        value: zolder
        effect: NoSchedule
    securityContext:
      privileged: true
