apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cilium
spec:
  interval: 5m
  chart:
    spec:
      chart: cilium
      version: 1.18.7
      sourceRef:
        kind: HelmRepository
        name: cilium
  values:
    upgradeCompatibility: "1.12"
    hubble:
      relay:
        enabled: true
        resources:
          requests:
            memory: 40Mi
            cpu: 5m
          limits:
            memory: 200Mi
            cpu: 250m
      metrics:
        enabled:
        - drop
        serviceMonitor:
          enabled: true
    kubeProxyReplacement: true
    k8sServiceHost: k8s-api.9ka.nl
    k8sServicePort: 6443
    ingressController:
      enabled: true
      loadbalancerMode: shared
      service:
        type: ClusterIP
        externalTrafficPolicy: ~
    prometheus:
      enabled: true
      serviceMonitor:
        enabled: true
    operator:
      prometheus:
        enabled: true
        serviceMonitor:
          enabled: true
      resources:
        requests:
          memory: 200Mi
          cpu: 10m
    securityContext:
      privileged: true
    resources:
      requests:
        memory: 550Mi
        cpu: 700m
