apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: zigbee2mqtt
spec:
  interval: 5m
  chart:
    spec:
      chart: zigbee2mqtt
      version: 1.42.0
      sourceRef:
        kind: HelmRepository
        name: zigbee2mqtt
  values:
    ingress:
      enabled: true
      ingressClassName: cilium
      hosts:
      - host: zigbee2mqtt.9ka.nl
        paths:
        - path: /
          pathType: Prefix
      annotations:
        external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
        external-dns.alpha.kubernetes.io/hostname: zigbee2mqtt.9ka.nl
        external-dns.alpha.kubernetes.io/target: 431113a6-4cf3-4a66-9750-17113ae2e689.cfargotunnel.com
    service:
      type: ClusterIP
    statefulset:
      storage:
        enabled: true
        storageClassName: nfs-nvme
      nodeSelector:
        feature.node.kubernetes.io/usb-ff_10c4_ea60.present: "true"
      tolerations:
      - effect: NoSchedule
        key: efgh.nl/location
        value: gangkast
    zigbee2mqtt:
      homeassistant:
        enabled: false
      mqtt:
        server: mqtt://mqtt:1883"
      serial:
        port: null