apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: node-feature-discovery-app
  namespace: flux-system
spec:
  interval: 10m
  path: "./clusters/9ka/node-feature-discovery/app/"
  prune: true
  timeout: 1m
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
  - name: node-feature-discovery-crd
