apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: node-feature-discovery-crd
  namespace: flux-system
spec:
  interval: 10m
  path: "./clusters/9ka/node-feature-discovery/crd/"
  prune: true
  timeout: 1m
  sourceRef:
    kind: GitRepository
    name: flux-system
