apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: vwsfriend-psql
spec:
  instances: 1
  storage:
    size: 2Gi
    storageClass: proxmox-zfs-nvme
  resources:
    limits:
      cpu: 300m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 200Mi
  bootstrap:
    initdb:
      database: vwsfriend
      owner: vwsfriend
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: vwsfriend-psql
spec:
  selector:
    matchLabels:
      cnpg.io/cluster: vwsfriend-psql
  podMetricsEndpoints:
  - port: metrics