apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: valkey
  namespace: netbox
spec:
  interval: 5m
  chartRef:
    kind: OCIRepository
    name: valkey
  values:
    fullnameOverride: netbox-valkey
    architecture: standalone
    primary:
      persistence:
        size: 1Gi
        storageClass: proxmox-zfs-nvme
    auth:
      existingSecret: netbox-valkey
      existingSecretPasswordKey: valkey-password
