apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: valkey
  namespace: netbox
spec:
  interval: 5m
  chartRef:
    kind: OCIRepository
    name: valkey
  values:
    fullnameOverride: netbox-valkey
    architecture: standalone
    master:
      persistence:
        size: 1Gi
        storageClass: proxmox-zfs-nvme
      tolerations:
      - operator: Equal
        key: efgh.nl/location
        value: zolder
        effect: NoSchedule
    auth:
      existingSecret: netbox-valkey
      existingSecretPasswordKey: valkey-password
