apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: netbox
spec:
  interval: 5m
  chartRef:
    kind: OCIRepository
    name: netbox
  values:
    existingSecret: netbox-secrets
    ingress:
      annotations:
        external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
        external-dns.alpha.kubernetes.io/hostname: netbox.9ka.nl
        external-dns.alpha.kubernetes.io/target: 431113a6-4cf3-4a66-9750-17113ae2e689.cfargotunnel.com
      className: cilium
      enabled: true
      hosts:
      - host: netbox.9ka.nl
        paths:
        - /
    persistence:
      storageClass: nfs-nvme
      accessMode: ReadWriteMany
    postgresql:
      enabled: false
    externalDatabase:
      existingSecretName: netbox-psql-app
      existingSecretKey: password
      host: netbox-psql-rw
      database: netbox
      username: netbox
    valkey:
      enabled: false
    tasksDatabase:
      host: netbox-valkey
      existingSecretName: netbox-valkey-users
      existingSecretKey: default
    cachingDatabase:
      host: netbox-valkey
      existingSecretName: netbox-valkey-users
      existingSecretKey: default
    resources:
      limits:
        cpu: 1000m
        memory: 1Gi
      requests:
        cpu: 500m
        memory: 768Mi
    worker:
      resources:
        limits:
          cpu: 1000m
          memory: 1Gi
        requests:
          cpu: 500m
          memory: 768Mi
    csrf:
      trustedOrigins:
      - https://netbox.9ka.nl
    remoteAuth:
      enabled: true
      backends:
      - netbox.authentication.RemoteUserBackend
      autoCreateUser: true
      header: cf-access-authenticated-user-email
      userEmail: cf-access-authenticated-user-email
      #groupHeader: HTTP_X_FORWARDED_GROUPS
      groupSeparator: ','
      defaultGroups: []
      defaultPermissions: {}
      groupSyncEnabled: true
      superuserGroups: []
      superusers: ['Jorik Jonker', 'jorik@kippendief.biz']
      staffGroups: []
      staffUsers: ['Jorik Jonker', 'jorik@kippendief.biz']
