apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: netbox
  namespace: netbox
spec:
  interval: 5m
  chartRef:
    kind: OCIRepository
    name: netbox
  values:
    nodeSelector:
      topology.kubernetes.io/region: thuis-svc
    tolerations:
    - operator: Equal
      key: efgh.nl/location
      value: zolder
      effect: NoSchedule
    existingSecret: netbox-secrets
    ingress:
      annotations:
        external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
        external-dns.alpha.kubernetes.io/hostname: netbox.9ka.nl
        external-dns.alpha.kubernetes.io/target: 431113a6-4cf3-4a66-9750-17113ae2e689.cfargotunnel.com
      className: cilium
      enabled: true
      hosts:
      - host: netbox.9ka.nl
        paths:
        - /
    persistence:
      storageClass: nfs-nvme
      accessMode: ReadWriteMany
    postgresql:
      enabled: false
    externalDatabase:
      existingSecretName: netbox-postgresql
      existingSecretKey: password
      host: netbox-postgresql-hl
      database: netbox
      username: netbox
    valkey:
      enabled: false
    tasksDatabase:
      host: netbox-valkey-headless
      existingSecretName: netbox-valkey
      existingSecretKey: valkey-password
    cachingDatabase:
      host: netbox-valkey-headless
      existingSecretName: netbox-valkey
      existingSecretKey: valkey-password
    resources:
      limits:
        cpu: 1000m
        memory: 1Gi
      requests:
        cpu: 500m
        memory: 768Mi
    housekeeping:
      nodeSelector:
        topology.kubernetes.io/region: thuis-svc
      tolerations:
      - operator: Equal
        key: efgh.nl/location
        value: zolder
        effect: NoSchedule
    worker:
      nodeSelector:
        topology.kubernetes.io/region: thuis-svc
      tolerations:
      - operator: Equal
        key: efgh.nl/location
        value: zolder
        effect: NoSchedule
      resources:
        limits:
          cpu: 1000m
          memory: 1Gi
        requests:
          cpu: 500m
          memory: 768Mi
    remoteAuth:
      enabled: true
      backends:
      - netbox.authentication.RemoteUserBackend
      autoCreateUser: true
      header: HTTP_X_FORWARDED_USER
      userEmail: HTTP_X_FORWARDED_EMAIL
      groupHeader: HTTP_X_FORWARDED_GROUPS
      groupSeparator: ','
      defaultGroups: []
      defaultPermissions: {}
      groupSyncEnabled: true
      superuserGroups: []
      superusers: ['Jorik Jonker']
      staffGroups: []
      staffUsers: ['Jorik Jonker']
