apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: netbox
  namespace: netbox
spec:
  interval: 5m
  chart:
    spec:
      chart: charts/netbox
      sourceRef:
        kind: GitRepository
        name: bootc
        namespace: flux-system
  values:
    existingSecret: netbox-secrets
    image:
      tag: v4.0.1
    ingress:
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt
      className: nginx
      enabled: true
      hosts:
      - host: netbox.9ka.nl
        paths:
        - /
      tls:
      - hosts:
        - netbox.9ka.nl
        secretName: netbox-tls
    persistence:
      storageClass: null
    postgresql:
      enabled: true
      auth:
        existingSecret: netbox-postgresql
        secretKeys:
          userPasswordKey: postgresql-password
          adminPasswordKey: postgresql-postgres-password
    redis:
      architecture: standalone
