apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: postgresql
  namespace: netbox
spec:
  interval: 5m
  chartRef:
    kind: OCIRepository
    name: postgresql
  values:
    primary:
      tolerations:
      - operator: Equal
        key: efgh.nl/location
        value: zolder
        effect: NoSchedule
    fullnameOverride: netbox-postgresql
    auth:
      database: netbox
      username: netbox
      existingSecret: netbox-postgresql
