apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: netbox
  namespace: netbox
spec:
  interval: 5m
  chart:
    spec:
      chart: netbox
      version: 5.0.0-beta.82
      sourceRef:
        kind: HelmRepository
        name: netbox
        namespace: flux-system
  values:
    existingSecret: netbox-secrets
    image:
      tag: v4.0.9
    ingress:
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt
        nginx.ingress.kubernetes.io/auth-url: "http://oauth2-proxy.oauth2-proxy.svc.cluster.local/oauth2/auth"
        nginx.ingress.kubernetes.io/auth-signin: "https://$host/oauth2/start?rd=$escaped_request_uri"
        nginx.ingress.kubernetes.io/auth-response-headers: "X-Forwarded-User,X-Forwarded-Groups,X-Forwarded-Email"
      className: nginx
      enabled: true
      hosts:
      - host: netbox.9ka.nl
        paths:
        - /
      tls:
      - hosts:
        - netbox.9ka.nl
        secretName: netbox-tls
    persistence:
      storageClass: null
    postgresql:
      enabled: false
    externalDatabase:
      existingSecretName: netbox-postgresql
      existingSecretKey: password
      host: netbox-postgresql-hl
      database: netbox
      username: netbox
    redis:
      enabled: false
    tasksRedis:
      host: netbox-redis-headless
      existingSecretName: netbox-redis
      existingSecretKey: redis-password
    cachingRedis:
      host: netbox-redis-headless
      existingSecretName: netbox-redis
      existingSecretKey: redis-password
    resources:
      limits:
        cpu: 1000m
        memory: 1Gi
      requests:
        cpu: 500m
        memory: 768Mi
    worker:
      resources:
        limits:
          cpu: 1000m
          memory: 1Gi
        requests:
          cpu: 500m
          memory: 768Mi
    remoteAuth:
      enabled: true
      backends:
      - netbox.authentication.RemoteUserBackend
      autoCreateUser: true
      header: HTTP_X_FORWARDED_USER
      userEmail: HTTP_X_FORWARDED_EMAIL
      groupHeader: HTTP_X_FORWARDED_GROUPS
      groupSeparator: ','
      defaultGroups: []
      defaultPermissions: {}
      groupSyncEnabled: true
      superuserGroups: []
      superusers: ['Jorik Jonker']
      staffGroups: []
      staffUsers: ['Jorik Jonker']
