apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: netbox
  namespace: netbox
spec:
  interval: 5m
  chart:
    spec:
      chart: netbox
      version: 4.1.1
      sourceRef:
        kind: HelmRepository
        name: bootc
        namespace: flux-system
  values:
    existingSecret: netbox-secrets
    image:
      tag: v3.5.6
    ingress:
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt
      enabled: true
      hosts:
      - host: netbox.9ka.nl
        paths:
        - /
      tls:
      - hosts:
        - netbox.9ka.nl
        secretName: netbox-tls
    persistence:
      storageClass: null
    postgres:
      enabled: true
