apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: redis
  namespace: netbox
spec:
  interval: 5m
  chart:
    spec:
      chart: redis
      version: 19.6.2
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  values:
    fullnameOverride: netbox-redis
    architecture: standalone
    auth:
      existingSecret: netbox-redis
      existingSecretPasswordKey: redis-password
