apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: valkey
spec:
  interval: 5m
  chartRef:
    kind: OCIRepository
    name: valkey
  values:
    fullnameOverride: netbox-valkey
    architecture: standalone
    primary:
      persistence:
        size: 1Gi
        storageClass: proxmox-zfs-nvme
    auth:
      existingSecret: netbox-valkey
      existingSecretPasswordKey: valkey-password
    image:
      repository: bitnamilegacy/valkey
      tag: 8.1.3-debian-12-r3