apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: postgresql
spec:
  interval: 5m
  chartRef:
    kind: OCIRepository
    name: postgresql
  values:
    fullnameOverride: netbox-postgresql
    primary:
      persistence:
        size: 1Gi
        storageClass: proxmox-zfs-nvme
    auth:
      database: netbox
      username: netbox
      existingSecret: netbox-postgresql
    image:
      repository: bitnamilegacy/postgresql
      tag: 17.6.0-debian-12-r4