apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: postgresql
  namespace: netbox
spec:
  interval: 5m
  chart:
    spec:
      chart: postgresql
      version: 16.2.1
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  values:
    fullnameOverride: netbox-postgresql
    auth:
      database: netbox
      username: netbox
      existingSecret: netbox-postgresql
