apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: valkey
spec:
  interval: 5m
  chartRef:
    kind: OCIRepository
    name: valkey
  values:
    global:
      imageRegistry: ghcr.io
    image:
      repository: valkey-io/valkey
    dataStorage:
      enabled: true
      size: 1Gi
      className: proxmox-zfs-nvme
    fullnameOverride: netbox-valkey
    resources:
      limits:
        cpu: 500m
        memory: 128Mi
      requests:
        cpu: 15m
        memory: 16Mi
    auth:
      enabled: true
      usersExistingSecret: "netbox-valkey-users"
      aclUsers:
        default:
          permissions: "~* &* +@all"