apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: netbox-psql
spec:
  instances: 1
  storage:
    size: 1Gi
    storageClass: proxmox-zfs-nvme
  resources:
    limits:
      cpu: 150m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 128Mi
  bootstrap:
    initdb:
      database: netbox
      owner: netbox
