apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: netbox
  namespace: netbox
  labels:
    app.kubernetes.io/name: netbox
spec:
  storageClassName: proxmox-zfs-nvme
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
