apiVersion: v1
data:
    redis-password: ENC[AES256_GCM,data:aLb3KnkaSRQAVYkPNC6Ukw==,iv:hPOXo353T3nWyqo1OEpZAzIq0YxWVxtbkKB0ecdNCbo=,tag:wjt/bTA3WjtJqCXqa6P07Q==,type:str]
kind: Secret
metadata:
    labels:
        app.kubernetes.io/name: netbox
    name: netbox-redis
    namespace: netbox
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    lastmodified: '2024-05-14T08:02:08Z'
    mac: ENC[AES256_GCM,data:+kghfmQ7VQvepRn654BzH7YIbUSmM+v8EKeHS0mqytEzNCLc4U+2uNMsO1iaT0LLYNvSXvlLYWY4Hw1cTNUQSPiTmJW7CANF1DtpJuN3kH1msLHCDIbiJ9JMmoI4NmAOa3FY8VhnKn5VdbGwrLUVBkjExRj+tAXt/aK1ZTBfM3Y=,iv:pp89jQBqL2Nrd5QFsxXsEQ/rdCUZltihBjZ94TiEDmk=,tag:3Wy0hPoQEr7/r+SBvaYntg==,type:str]
    pgp:
    -   created_at: '2024-05-14T08:02:08Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA59YQxrIsWI6ARAAsZF6nmNvBRweAwQDI0VCciTOQEyU+E6xfVUBluV4qygi
            l/qIwNJSo5DgWd/jW6YSkZz156xtaq9BNrJx1GXx5jbLevQ58d2VnVEoKkcHIuzu
            IOxc8+bezdcseAif3V+Hp0mZB3KkizRFUP4UxT5GHXVk2M1q8JhKJAI14v4wEyx0
            b5nuGUe84/NPGLAd5tpAKIfjofzburhO7JsdKMhKAQS4wOat73vCyDOMao8yWGui
            eQbUGrkv3UpoDNMkC2qhkMhjlIhdH2L8+aj+EENZDt/GUHea3ighaOOTZHBkZotX
            YkQ4oT9IZiKISOorvpvyNvEXiRm+EINHFEthj7ISUPr6k4PPFrDxCI3G2hwlaZax
            F2Wsc/l46V9On/dVfmXIEO0sOUZzoEEJv29uWyp6G1xtYWXCXNwMD4zY1M2aWKu9
            Tn+VZaIWoZfugjuzJcocjrj3bm++ig0+nM0hnS+XbeKqvPctEsa1VVUxf8x/kW0L
            pJz8cFkxPESCjX08DHfSzMpjbZVSRyHVSGwMRplqI5Po5K0ZVVVIYqjroRE5BPyS
            Dmap2OVSNHjcVc5vJbyy5EOORSxXmZkPZUQhFJv2Lv6eLQphC9N40GvXDe7zg21D
            Lz/2PJlXA1Sccd0NPUwkSEJX6QpbRB/1llDrbcfDbiGUcwSwj3i9/UPZbGH4VVTS
            XAGFSX8UP9uGxipPKexWjBYlvC3XfjgPYhkK3OVYfgYX72I05iGyeJ2M8new9uDG
            dYbZCFoDozoBMFfheJic3VZAT6BkXEjuXcGiNEhrItPlDFo8lByK2Ia/QDqH
            =23/U
            -----END PGP MESSAGE-----
        fp: 4D72B62BB844B05E12DEC3A9A3AEC49250A67E2A
    encrypted_regex: ^(data|stringData)$
    version: 3.6.1
