{
 "title": "Proxmox VE",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(pve_memory_usage_bytes{id!=\"node/pve\"}) by (id)",
     "legendFormat": "{{ id }}"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 9, "x": 9, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(pve_cpu_usage_ratio{id!=\"node/pve\"}) by (id)",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "Net/in",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(pve_network_receive_bytes[1m])) by (id)",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "Net/out",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 9, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(pve_network_transmit_bytes[1m])) by (id)",
     "legendFormat": "{{id}}"
    }
   ]
  }
 ]
}