apiVersion: v1
kind: Secret
metadata:
    name: alertmanager-ntfy
    labels:
        app.kubernetes.io/instance: alertmanager-ntfy
        app.kubernetes.io/name: alertmanager-ntfy
stringData:
    auth.yml: ENC[AES256_GCM,data:Hp3muWzGLfkRJc94VyLveFQZ3KaWOzVyPokGxldjJI3AN5YQnwwfxmKNdwEt1eAkwlZ4d960mQuBteQ3jxmKqfK8D4nnJDU/NVqcDHT/8Sqxtls19QQhHzpEVdQzWPIezpbRB0Zyj9Dgk46OmVlB9u/USMkzRSABsUJ8Y/SBPB0oRDT9Jc4iOvaE4vaKddk1pw==,iv:sZ/QZIU3exax10k5foBD/ZCF3yvPldV7ERVh/Gqdefo=,tag:oCDSXRSfupvd/lAqZ4FdrQ==,type:str]
sops:
    lastmodified: "2026-06-29T13:01:35Z"
    mac: ENC[AES256_GCM,data:4Syny2RDFQpDTT0q5xx2aH4AyBchLaXmy4lVOcmCB3QzAQw3wlfLWIIJakonTRdu8dN0BqAw7iBvE5TrquR2pfjl1lyGErrAnSvnYKzEGh/TMZRCb7PRGc31DqqZ+F8EHOQlDIk5DnIwZPSt7B/k/td9Fz56mUsNOv6Xc/Z/icg=,iv:Mn8qsfEnZDhQnkl2v6UDpkwQCP5PQbHs2tl/xE/YDho=,tag:lFMoMtc+oEqQYC12ulpb6w==,type:str]
    pgp:
        - created_at: "2026-06-29T13:01:35Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA59YQxrIsWI6AQ/9GtgCjSflU3oFhEXZyI3omgFhhZoaiHVxdd9AbmKnAOvR
            5HnNnwFAvDpmrwgqLdC/YyO/DLuOS71Bp4L74lAwdV4dE+Hm54UAHknG2XIVt71Z
            baXdpzJ3MUK8ARCOACdDbAC5Aq7EkLFhfgYq76eiUwbMX7rnaxdQbm1bkTe24hr8
            uJJexLF7iNd0pMyzPE8kFszupqOnWi+91LnM1geYUSxR664mBSmY48Qu2025cpM/
            BLZQs8Iaiqogwpd/rJSTIBpiz5M+x4pvuwZqQ96aP57mgLm4zBQo/FpHUzsixX7h
            kzVzCFAahlshdTW4gvkSw3622aSG0F/hfBpIcAm2Vp7RPCYJqYWScyGmKSRCmw1O
            iZlRgYsveF03FEp1bppRmy2lxl5GvR0F9Y/mPc4fL3DYUTIEEkkkQNV5eeoy7jze
            HMMJkDjA0oSuR8hqxgE2+385E0DT+BSkIUgDOu+COS0MGceLLc26J50sf7fwXsZG
            ZLa7i9bqXamnhyRDaZD0ApYO3ZC/1DVsjql8hbeb5LMdaEEFyEO4dW+Tl9l0eNwg
            3yacx058I26BOgwuop1ZtP0Sn4Ohpj86UrOyB8MboL3CazcBenFSU7tx2lajyDW/
            PINxi6fxzxkcMwaAv0DJY0AIa7nUNPmmEzls2j89yhGAZECB2d79A586KRFsls3S
            XgH7zFT2951gaTiOJslEn9IEbnBcn/oJ3oUGlKgxOTbKCNwW/0alE6ION3kRDeES
            1U5/RyvPTGYSnGLORK3hKtcI64Go7MVFqG3cxhbgadKVK46mPkBG6ES7Zm69OVw=
            =dLfk
            -----END PGP MESSAGE-----
          fp: 4D72B62BB844B05E12DEC3A9A3AEC49250A67E2A
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
