apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: ntfy
spec:
  interval: 1h
  layerSelector:
    mediaType: "application/vnd.cncf.helm.chart.content.v1.tar+gzip"
    operation: copy
  url: oci://ghcr.io/helmforgedev/helm/ntfy
  ref:
    tag: 1.1.11