apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cilium
  namespace: kube-system
spec:
  interval: 5m
  chart:
    spec:
      chart: cilium
      version: 1.12.2
      sourceRef:
        kind: HelmRepository
        name: cilium
        namespace: flux-system
  values:
    upgradeCompatibility: "1.9"
    hubble:
      relay:
        enabled: true
      metrics:
        enabled:
        - drop
        serviceMonitor:
          enabled: true
    kubeProxyReplacement: strict
    k8sServiceHost: 9ka.nl
    k8sServicePort: 6443
    prometheus:
      enabled: true
      serviceMonitor:
        enabled: true
    operator:
      prometheus:
        enabled: true
        serviceMonitor:
          enabled: true
    securityContext:
      privileged: false
  postRenderers:
  - kustomize:
      patchesStrategicMerge:
      - apiVersion: apps/v1
        kind: DaemonSet
        metadata:
          name: cilium
          namespace: kube-system
        spec:
          template:
            spec:
              containers:
                - name: cilium-agent
                  securityContext:
                    capabilities:
                      add:
                      - CHOWN
                      - KILL
                      - NET_ADMIN
                      - NET_RAW
                      - IPC_LOCK
                      - SYS_RESOURCE
                      - PERFMON
                      - BPF
                      - DAC_OVERRIDE
                      - FOWNER
                      - SETGID
                      - SETUID
                      - SYS_ADMIN  # still needed for cgroup mounting :-(
              initContainers:
                - name: clean-cilium-state
                  securityContext:
                    capabilities:
                      add:
                      - NET_ADMIN
                      - SYS_RESOURCE
                      - PERFMON
                      - BPF
