apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: node-exporter
  labels:
    app: external-node-exporters
spec:
  jobLabel: node-exporter
  endpoints:
  - port: metrics
    interval: 60s
    relabelings:
    - sourceLabels:
      - "__meta_kubernetes_endpoint_node_name"
      targetLabel: node_name
  selector:
    matchLabels:
      app: external-node-exporters
---
apiVersion: v1
kind: Service
metadata:
  name: external-node-exporter
  labels:
    app: external-node-exporters
spec:
  type: ClusterIP
  ports:
  - name: metrics
    port: 9000
    targetPort: metrics
---
apiVersion: v1
kind: Endpoints
metadata:
  name: external-node-exporter
  labels:
    app: external-node-exporters
subsets:
- addresses:
  - ip: 172.21.42.1
    nodeName: hydrogen
  - ip: 172.21.46.2
    nodeName: helium
  - ip: 172.21.42.3
    nodeName: lithium
  - ip: 172.21.42.10
    nodeName: neon
  - ip: 172.21.42.7
    nodeName: nitrogen
  - ip: 172.21.42.15
    nodeName: phosphorus
  - ip: 172.21.48.1
    nodeName: pve
  - ip: 172.21.42.14
    nodeName: silicon
  ports:
  - name: metrics
    port: 9200
    protocol: TCP
