apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: node-exporter
  labels:
    app: external-node-exporters
spec:
  jobLabel: node-exporter
  endpoints:
  - port: metrics
    interval: 60s
    relabelings:
    - sourceLabels:
      - "__meta_kubernetes_endpoint_node_name"
      targetLabel: node_name
  selector:
    matchLabels:
      app: external-node-exporters
---
apiVersion: v1
kind: Service
metadata:
  name: external-node-exporter
  labels:
    app: external-node-exporters
spec:
  type: ClusterIP
  ports:
  - name: metrics
    port: 9000
    targetPort: metrics
---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: external-node-exporter
  labels:
    app: external-node-exporters
addressType: IPv4
ports:
- name: metrics
  port: 9200
  protocol: TCP
endpoints:
- addresses:
  - 172.21.42.1
  hostname: hydrogen
  nodeName: hydrogen
  conditions:
    ready: true
- addresses:
  - 172.21.42.3
  hostname: lithium
  nodeName: lithium
  conditions:
    ready: true
- addresses:
  - 172.21.42.7
  hostname: nitrogen
  nodeName: nitrogen
  conditions:
    ready: true
- addresses:
  - 172.21.42.14
  hostname: silicon
  nodeName: silicon
  conditions:
    ready: true
- addresses:
  - 172.21.42.15
  hostname: phosphorus
  nodeName: phosphorus
  conditions:
    ready: true
- addresses:
  - 172.21.46.2
  hostname: helium
  nodeName: helium
  conditions:
    ready: true
- addresses:
  - 172.21.48.1
  hostname: pve
  nodeName: pve
  conditions:
    ready: true
