apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: haproxy
  labels:
    app: haproxy
spec:
  jobLabel: haproxy
  endpoints:
  - port: metrics
    interval: 300s
    relabelings:
    - sourceLabels:
      - "__meta_kubernetes_endpoint_node_name"
      targetLabel: node_name
  selector:
    matchLabels:
      app: haproxy
---
apiVersion: v1
kind: Service
metadata:
  name: haproxy
  labels:
    app: haproxy
spec:
  type: ClusterIP
  ports:
  - name: metrics
    port: 9000
    targetPort: metrics
---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: haproxy
  labels:
    app: haproxy
addressType: IPv4
ports:
- name: metrics
  port: 8404
  protocol: TCP
endpoints:
- addresses:
  - 172.21.46.2
  conditions:
    ready: true
  nodeName: helium
  hostname: helium
