apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: ipsec-exporter
  labels:
    app: ipsec-exporter
spec:
  jobLabel: ipsec-exporter
  endpoints:
  - port: metrics
    interval: 300s
    relabelings:
    - sourceLabels:
      - "__meta_kubernetes_endpoint_node_name"
      targetLabel: node_name
  selector:
    matchLabels:
      app: ipsec-exporter
---
apiVersion: v1
kind: Service
metadata:
  name: ipsec-exporter
  labels:
    app: ipsec-exporter
spec:
  type: ClusterIP
  ports:
  - name: metrics
    port: 9903
    targetPort: metrics
---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: ipsec-exporter
  labels:
    app: ipsec-exporter
addressType: IPv4
ports:
- name: metrics
  port: 9903
  protocol: TCP
endpoints:
- addresses:
  - 172.21.48.1
  conditions:
    ready: true
  nodeName: pve
  hostname: pve
