apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: powerdns-recursor
  namespace: monitoring
  labels:
    app: powerdns-recursor
spec:
  jobLabel: powerdns-recursor
  endpoints:
  - port: metrics
    interval: 300s
    relabelings:
    - sourceLabels:
      - "__meta_kubernetes_endpoint_node_name"
      targetLabel: node_name
  selector:
    matchLabels:
      app: powerdns-recursor
---
apiVersion: v1
kind: Service
metadata:
  name: powerdns-recursor
  namespace: monitoring
  labels:
    app: powerdns-recursor
spec:
  type: ClusterIP
  ports:
  - name: metrics
    port: 9000
    targetPort: metrics
---
apiVersion: v1
kind: Endpoints
metadata:
  name: powerdns-recursor
  namespace: monitoring
  labels:
    app: powerdns-recursor
subsets:
- addresses:
  - ip: 172.21.42.1
    nodeName: hydrogen
  ports:
  - name: metrics
    port: 8082
    protocol: TCP
- addresses:
  - ip: 172.21.48.1
    nodeName: pve
  ports:
  - name: metrics
    port: 8082
    protocol: TCP
