apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: zrepl
  labels:
    app: zrepl
spec:
  jobLabel: zrepl
  endpoints:
  - port: metrics
    interval: 300s
    relabelings:
    - sourceLabels:
      - "__meta_kubernetes_endpoint_node_name"
      targetLabel: node_name
  selector:
    matchLabels:
      app: zrepl
---
apiVersion: v1
kind: Service
metadata:
  name: zrepl
  labels:
    app: zrepl
spec:
  type: ClusterIP
  ports:
  - name: metrics
    port: 7294
    targetPort: metrics
---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: zrepl
  labels:
    app: zrepl
addressType: IPv4
ports:
- name: metrics
  port: 7294
  protocol: TCP
subsets:
- addresses:
  - 172.21.46.2
  conditions:
    ready: true
  nodeName: helium
  hostname: helium
- addresses:
  - 172.21.48.1
  conditions:
    ready: true
  nodeName: pve
  hostname: pve
