apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: smartevse-telegraf
  namespace: mqtt
spec:
  interval: 5m
  chart:
    spec:
      chart: telegraf
      version: 1.8.37
      sourceRef:
        kind: HelmRepository
        name: influxdata
        namespace: flux-system
  values:
    env:
    - name: INFLUXDB_TOKEN
      valueFrom:
        secretKeyRef:
          name: smartevse-telegraf
          key: token
    config:
      agent:
        flush_interval: 1m
        interval: 1m
        omit_hostname: true
      inputs:
      - mqtt_consumer:
          data_format: value
          data_type: float
          servers:
          - tcp://mosquitto:1883
          topics:
          - SmartEVSE-35435
      outputs:
      - influxdb_v2:
          bucket: smartevse
          bucket_tag: gareelhoek
          organization: influxdata
          token: '${INFLUXDB_TOKEN}'
          urls:
          - http://influxdb2.influxdb
    metrics:
      internal:
        enabled: false
    service:
      enabled: false
