---
apiVersion: v1
kind: ConfigMap
metadata:
  name: datasource-nuts
  namespace: monitoring
  labels:
    grafana_datasource: "1"
data:
  nuts.yaml: |-
    apiVersion: 1
    datasources:
    - name: nuts
      type: influxdb
      access: proxy
      url: http://influxdb.influxdb:8086/
      database: nuts
      user: $INFLUX_USER
      secureJsonData:
        password: $INFLUX_PASSWORD
      editable: false
...
