apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nfs-nvme
spec:
  interval: 5m
  chart:
    spec:
      chart: nfs-subdir-external-provisioner
      version: 4.0.18
      sourceRef:
        kind: HelmRepository
        name: nfs-subdir-external-provisioner
  values:
    nfs:
      path: /rpool/9ka-nfs-nvme
      server: nfs-9ka-nvme.9ka.nl
      mountOptions:
      - noatime
      - async
    storageClass:
      archiveOnDelete: false
      defaultClass: false
      name: nfs-nvme
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: topology.kubernetes.io/region
              operator: In
              values:
              - thuis-svc
    resources:
      requests:
        cpu: 50m
        memory: 20Mi
      limits:
        cpu: 250m
        memory: 64Mi
  postRenderers:
  - kustomize:
      patches:
      - patch: |
          apiVersion: storage.k8s.io/v1
          kind: StorageClass
          metadata:
            name: nfs-nvme
          allowedTopologies:
          - matchLabelExpressions:
            - key: efgh.nl/location
              values:
              - thuis
