apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nfs-fast
  namespace: storage
spec:
  interval: 5m
  chart:
    spec:
      chart: nfs-subdir-external-provisioner
      version: 4.0.18
      sourceRef:
        kind: HelmRepository
        name: nfs-subdir-external-provisioner
  values:
    nfs:
      path: /ssd/9ka-fast
      server: pve.virt.efgh.nl
      mountOptions:
      - noatime
      - async
    storageClass:
      archiveOnDelete: false
      defaultClass: true
      name: nfs-fast
    resources:
      requests:
        cpu: 50m
        memory: 16Mi
      limits:
        cpu: 250m
        memory: 64Mi
