apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: etcd
spec:
  groups:
  - name: etcd
    rules:
    - alert: EtcdWrongNumberMembers
      expr: count(etcd_server_id) % 2 == 0
      for: 5m
      labels:
        severity: critical
      annotations:
        summary: Etcd wrong number of members
        message: Etcd needs to have an odd number of members
    - alert: EtcdNoLeader
      expr: etcd_server_has_leader == 0
      for: 0m
      labels:
        severity: critical
      annotations:
        summary: Etcd node {{ $labels.node_name }} has no leader
        message: Etcd node {{ $labels.node_name }} thinks it has no leader
    - alert: EtcdHighLeaderChange
      expr: increase(etcd_server_leader_changes_seen_total[10m]) > 2
      for: 0m
      labels:
        severity: warning
      annotations:
        summary: Etcd high number of leader changes on {{ $labels.node_name }}
        message: Etcd leader changed more than 2 times during 10 minutes
    - alert: EtcdHighNumberOfFailedHttpRequests
      expr: sum(rate(etcd_http_failed_total[1m])) BY (method) / sum(rate(etcd_http_received_total[1m])) BY (method) > 0.01
      for: 2m
      labels:
        severity: warning
      annotations:
        summary: Etcd high number of failed HTTP requests on {{ $labels.node_name }}
        message: More than 1% HTTP failure detected in Etcd
    - alert: EtcdHighNumberOfFailedHttpRequests
      expr: sum(rate(etcd_http_failed_total[1m])) BY (method) / sum(rate(etcd_http_received_total[1m])) BY (method) > 0.05
      for: 2m
      labels:
        severity: critical
      annotations:
        summary: Etcd high number of failed HTTP requests on {{ $labels.node_name }}
        message: More than 5% HTTP failure detected in Etcd
    - alert: EtcdHttpRequestsSlow
      expr: histogram_quantile(0.99, rate(etcd_http_successful_duration_seconds_bucket[1m])) > 0.15
      for: 2m
      labels:
        severity: warning
      annotations:
        summary: Etcd HTTP requests are slow on {{ $labels.node_name }}
        message: HTTP requests slowing down, 99th percentil is over 0.15s
    - alert: EtcdMemberCommunicationSlow
      expr: histogram_quantile(0.99, rate(etcd_network_peer_round_trip_time_seconds_bucket[1m])) > 0.15
      for: 2m
      labels:
        severity: warning
      annotations:
        summary: Etcd member communication slow on {{ $labels.node_name }}
        message: Etcd member communication slowing down, 99th percentil is over 0.15s
    - alert: EtcdHighNumberOfFailedProposals
      expr: increase(etcd_server_proposals_failed_total[1h]) > 5
      for: 2m
      labels:
        severity: warning
      annotations:
        summary: Etcd high number of failed proposals on {{ $labels.node_name }}
        message: Etcd server got more than 5 failed proposals past hour
    - alert: EtcdHighFsyncDurations
      expr: histogram_quantile(0.99, rate(etcd_disk_wal_fsync_duration_seconds_bucket[1m])) > 0.5
      for: 2m
      labels:
        severity: warning
      annotations:
        summary: Etcd high fsync durations on {{ $labels.node_name }}
        message: Etcd WAL fsync duration increasing, 99th percentil is over 0.5s
    - alert: EtcdHighCommitDurations
      expr: histogram_quantile(0.99, rate(etcd_disk_backend_commit_duration_seconds_bucket[1m])) > 0.25
      for: 2m
      labels:
        severity: warning
      annotations:
        summary: Etcd high commit durations on {{ $labels.node_name }}
        message: Etcd commit duration increasing, 99th percentil is over 0.25s
    - alert: EtcdFailedSendingHeartbeats
      expr: increase(etcd_server_heartbeat_send_failures_total[5m]) > 1
      for: 2m
      labels:
        severity: warning
      annotations:
        summary: Etcd has failed to send heartbeats on {{ $labels.node_name }}
        message: Etcd has failed to send {{ $value }} heartbeats in past 5 minutes
