apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: flux
spec:
  groups:
  - name: flux
    rules:
    - alert: FluxNotReconciling
      expr: gotk_resource_info{ready!="True"}>0
      for: 10m
      labels:
        severity: warning
      annotations:
        summary: Flux resource {{ $labels.customresource_kind }} {{ $labels.name }} not reconciling
        description: Flux {{ $labels.customresource_kind }} {{ $labels.name }} in namespace {{ $labels.namespace }} exporting to namespace {{ $labels.exported_namespace }} is not reconciling
