apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: ipmi
  namespace: monitoring
spec:
  groups:
  - name: ipmi
    rules:
    - alert: IPMISELFillingUp
      annotations:
        summary: IPMI SEL on {{ $labels.node_name }} is running out of space
        message: IPMI SEL on {{ $labels.node_name }} is running out of space in the next 24 hours
      expr: predict_linear(ipmi_sel_free_space_bytes[6h], 24*60*60) <= 0
      labels:
        severity: warning
    - alert: IPMISensorAbnormal
      annotations:
        summary: IPMI Sensor {{ $labels.name }} on {{ $labels.node_name }} in abnormal state
        message: IPMI Sensor {{ $labels.name }} ({{ $labels.type }}, id {{ $labels.id }}) on {{ $labels.node_name }} is not in nominal ({{ $value }}) state
      expr: |-
        (
          ipmi_fan_speed_state != 0
        or
          ipmi_power_state != 0
        or
          ipmi_sensor_state != 0
        or
          ipmi_temperature_state != 0
        or
          ipmi_voltage_state != 0
        )
      labels:
        severity: critical
