apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: ipsec
spec:
  groups:
  - name: ipsec
    rules:
    - alert: IPSecNotUp
      annotations:
        summary: IPSec is not UP
        message: IPSec is not UP on {{ $labels.node_name }}
      expr: ipsec_up != 1
      labels:
        severity: critical
