apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: node-cpu
spec:
  groups:
  - name: node-cpu
    rules:
    - alert: HostHighCpuLoad
      expr: 100 - (avg by(instance) (irate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 80
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: "Host high CPU load (instance {{ $labels.node_name }})"
        description: "CPU load is > 80%\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"
    - alert: HostHighIOWait
      expr: avg by (node_name) (rate(node_cpu_seconds_total{mode="iowait"}[5m])) > 0.25
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: "CPU iowait is high"
        description: "CPU iowait > 25%. A high iowait means that you are disk or network bound."
