apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: node-generic
spec:
  groups:
  - name: node-generic
    rules:
    - alert: Booted
      annotations:
        summary: 'Node {{ $labels.node_name }} has booted'
        message: '{{ $labels.node_name }} was booted {{ $value | humanizeDuration }} ago'
      expr: (time() - node_boot_time_seconds) < 300
      labels:
        severity: warning
    - alert: HostContextSwitching
      expr: (rate(node_context_switches_total[5m])) / (count without(cpu, mode) (node_cpu_seconds_total{mode="idle"})) > 1000
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: "Host context switching (instance {{ $labels.node_name }})"
        description: "Context switching is growing on node (> 1000 / s)\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"
