apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: velero
  namespace: monitoring
spec:
  groups:
  - name: velero
    rules:
    - alert: VeleroBackupPartialFailures
      annotations:
        summary: Velero backup {{ $labels.schedule }} has partialy failed backups.
        message: Velero backup {{ $labels.schedule }} has {{ $value }} partialy failed backups in past 24h.
      expr: sum by (schedule) (increase(velero_backup_partial_failure_total{schedule!=""}[24h])) > 0
      for: 1m
      labels:
        severity: warning
    - alert: VeleroBackupFailures
      annotations:
        summary: Velero backup {{ $labels.schedule }} has failed backups.
        message: Velero backup {{ $labels.schedule }} has {{ $value }} failed backups in past 24h.
      expr: sum by (schedule) (increase(velero_backup_failure_total{schedule!=""}[24h])) > 0
      for: 1m
      labels:
        severity: critical
