apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cloudflared
  namespace: ingress
spec:
  interval: 5m
  chart:
    spec:
      chart: cloudflare-tunnel
      version: 0.3.2
      sourceRef:
        kind: HelmRepository
        name: cloudflare
  values:
    image:
      tag: 2025.8.1 # repo=docker.io/cloudflare/cloudflared
    cloudflare:
      tunnelName: "thuis-svc"
      tunnelId: "431113a6-4cf3-4a66-9750-17113ae2e689"
      secretName: cloudflare-secrets
      ingress:
      - hostname: "*.9ka.nl"
        service: "http://cilium-ingress.cilium:80"
        originRequest:
          noTLSVerify: true
      - hostname: "*.boeventronie.net"
        service: "http://cilium-ingress.cilium:80"
        originRequest:
          noTLSVerify: true
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 1000m
        memory: 256Mi
    replicaCount: 1
