apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: ingress
spec:
  interval: 5m
  chart:
    spec:
      chart: ingress-nginx
      version: 4.9.1
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: flux-system
  values:
    controller:
      allowSnippetAnnotations: false
      config:
        use-proxy-protocol: "true"
      service:
        type: NodePort
        nodePorts:
          http: 30080
          https: 30443
      metrics:
        enabled: true
        serviceMonitor:
          enabled: true
          additionalLabels:
            release: monitoring
      resources:
        requests:
          cpu: 100m
          memory: 150Mi
        limits:
          cpu: 2
          memory: 500Mi
      ingressClassResource:
        default: true
    defaultBackend:
      resources:
        requests:
          cpu: 10m
          memory: 20Mi
        limits:
          cpu: 10m
          memory: 20Mi
