apiVersion: v1
data:
    apiKey: ENC[AES256_GCM,data:jNDXLjdLPoqPTDRXNRB1ECiUkqZ0cGClOt6UABYkAlNd13z597osMmbGGtthuwjV2DHQhExcHHU=,iv:OEHsf3aPbOJeluU0M4fU6B7zGvnz50W/rARWcCQcpcU=,tag:lqGzBqgRkPW4jZwktc2YSQ==,type:str]
    email: ENC[AES256_GCM,data:Io+j8GrQrdlxzOIHaszrn/dsg84=,iv:/VJQKlCc3Uwre2lSQlRwzr3DdllKdfo4aOfei4UaQU0=,tag:wsEmh5kInxddKPSOBuNu7A==,type:str]
    credentials.json: ENC[AES256_GCM,data:tff5P8PJzVYa1PQc9pu20SwqtBisG6kgKC2oroFiRva2sLoQ3684Vn1yVmp2YhM0FRk41pBt5J1SrB4g9A13PbdtT6TgWCYjzZnph9oa+QhrKHrVTbJnFk9O7CjsNE4F2wMiH4HkWb5+KGb3Y4pl2JeeFL9B6iWxpzSYPsQuzmik4/8ehSmBKq83Dxqk8piEsuxlVdQLcrVQyQnkmyd8PFo31NPuQssc9LwIcCx/eJF9x8EMoLB7p0AnVPcixPx1UTi5hhwoM482f6zXhba99Zp+x7aLoIKi,iv:mZfno06O7v6DcnRIfMMol48WmhXzk3j2DGFmBTVEBxU=,tag:esB6efNKqMUIZpf29gOjGQ==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: cloudflare-secrets
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    lastmodified: '2025-09-24T18:48:44Z'
    mac: ENC[AES256_GCM,data:gihX4/CGMgyGhDGZmmIASQ5UpVJfamynU4TOnm22D3jjOnMzcjqzJrpEyXM5DaHpfw/5c/xPkL4ODFPT2HJyU51vI5lU1YSt014zMg9vsOySeMzhxlZeAw+In+BOfDuouSmecZ8wjcY7YmZKK9h2ISZH33a5xUMb4+96rvfmzOg=,iv:oOsD9dyx14k7ugizYiqkTLthfD7hFY5pos4aPkeXg/o=,tag:T7HR6NI6ptT3gobdJssn6g==,type:str]
    pgp:
    -   created_at: '2025-06-25T10:06:18Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA59YQxrIsWI6AQ//dnkmpEY84Iy1KV2hfSa/WlH5I203zzTQPJBmldXYyRpU
            W6ZTSDUXmXLzN+qF9L9sYkOmO1eSVZAw3cyfffp43ZS35fRDqCR1sh09zBe095mc
            bj30pc1S2gwB/4gDEfgxfPnHRPxnv5jX/l4njzFBEQLnaL5O5rz1lIIv6vJ/sVWj
            NFhWwAUPsBLdohCnXsCxBuRXXO+ghanY60qn0YHdTJenrbBCG+tTgO93tVctpYYA
            Ee+EI2ettRoWfu4TnJuMg2gPGlb1pIAlzLRLB77r/I06Ounla6yOjwXjq/pGikrZ
            ud7HmRYyZoa9Y46jxPk1VhIKwYQXZBjXUfvcm7sS8NTvKLl/yRr2qaUWJj5Wacuz
            /NGPpd6KSQaW5EusmIm1LJ24P+1/aFjDBsV5ssuI/vZMJsVKtL6xG8uNkEJJX53U
            9lcEpDQfJUfex/Rj5HMYx6iMNqnTxVakTlw1GK+eWn4NryTM9Rzr+yKUaUeRasnp
            dhtIhJJYRptF+Vyk++Qym4dPgyALSS8IJErY19NQ0ccB+VUQhw5n9BadwKUv4J6Q
            pulZdk3K28nMl1LITHQPxy8ei+Ed1QB4eDoSpd0NkqzdEvTqWqnwP5Xf1XKOON+O
            SOu7LP7kdGcq/24OYtzLhyZEY5eQud3P2QYn4dhSjLkyi6L2P03JzDc1rAT98bjS
            XAF858odWQR+vDKWJ2SyMWQQRY7cTkaJLwwUKh7SbcMulJi2sIjylFWcMciuAomt
            DHe8iRzw1STR3zkDIu9yizBb3AoZGEG3gQIC5my2KFtJkvrDa6NsBprRQcDi
            =0FPS
            -----END PGP MESSAGE-----
        fp: 4D72B62BB844B05E12DEC3A9A3AEC49250A67E2A
    encrypted_regex: ^(data|stringData)$
    version: 3.6.1
