apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vaultwarden
  namespace: vaultwarden
spec:
  interval: 5m
  chart:
    spec:
      chart: vaultwarden
      version: 1.2.6
      sourceRef:
        kind: HelmRepository
        name: gissilabs
  values:
    image:
      tag: 1.34.3-alpine # repo=docker.io/vaultwarden/server
    vaultwarden:
      domain: https://brs.9ka.nl
      allowSignups: false
      signupDomains: kippendief.biz
      allowInvitation: true
      smtp:
        enabled: true
        from: jorik@efgh.nl
        fromName: Jorik Jonker
        host: pve.virt.efgh.nl
        port: 25
        security: off
    ingress:
      enabled: true
      className: cilium
      host: brs.9ka.nl
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt
      tls:
      - secretName: vaultwarden-tls
        hosts:
        - brs.9ka.nl
    persistence:
      enabled: true
      storageClass: nfs-nvme
      size: 256Mi
    resources:
      requests:
        cpu: 50m
        memory: 60Mi
      limits:
        cpu: 250m
        memory: 128Mi
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: topology.kubernetes.io/region
              operator: In
              values:
              - thuis-svc
    tolerations:
    - operator: Equal
      key: efgh.nl/location
      value: zolder
      effect: NoSchedule
