apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vaultwarden
  namespace: vaultwarden
spec:
  interval: 5m
  chart:
    spec:
      chart: vaultwarden
      version: 1.0.0
      sourceRef:
        kind: HelmRepository
        name: gissilabs
        namespace: flux-system
  values:
    image:
      tag: 1.30.1
    vaultwarden:
      domain: https://brs.9ka.nl
      allowSignups: false
      signupDomains: kippendief.biz
      allowInvitation: true
      smtp:
        enabled: true
        from: jorik@efgh.nl
        fromName: Jorik Jonker
        host: pve.virt.efgh.nl
        port: 25
        security: off
    ingress:
      enabled: true
      className: nginx
      host: brs.9ka.nl
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt
      tls:
      - secretName: vaultwarden-tls
        hosts:
        - brs.9ka.nl
    persistence:
      enabled: true
    resources:
      requests:
        cpu: 50m
        memory: 60Mi
      limits:
        cpu: 250m
        memory: 100Mi
