apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vaultwarden
spec:
  interval: 5m
  chart:
    spec:
      chart: vaultwarden
      version: 1.3.0
      sourceRef:
        kind: HelmRepository
        name: gissilabs
  values:
    image:
      tag: 1.35.0-alpine # repo=docker.io/vaultwarden/server
    vaultwarden:
      domain: https://brs.9ka.nl
      allowSignups: false
      signupDomains: kippendief.biz
      allowInvitation: true
      smtp:
        enabled: true
        from: jorik@efgh.nl
        fromName: Jorik Jonker
        host: pve.virt.efgh.nl
        port: 25
        security: off
    ingress:
      enabled: true
      className: cilium
      host: brs.9ka.nl
      annotations:
        external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
        external-dns.alpha.kubernetes.io/hostname: brs.9ka.nl
        external-dns.alpha.kubernetes.io/target: 431113a6-4cf3-4a66-9750-17113ae2e689.cfargotunnel.com
    persistence:
      enabled: true
      storageClass: nfs-nvme
      size: 256Mi
    resources:
      requests:
        cpu: 50m
        memory: 60Mi
      limits:
        cpu: 250m
        memory: 128Mi
