apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mosquitto
  namespace: mqtt
  labels:
    app.kubernetes.io/name: mosquitto
    app.kubernetes.io/part-of: mqtt
    app.kubernetes.io/instance: mosquitto
spec:
  serviceName: mosquitto
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: mosquitto
      app.kubernetes.io/part-of: mqtt
      app.kubernetes.io/instance: mosquitto
  template:
    metadata:
      labels:
        app.kubernetes.io/name: mosquitto
        app.kubernetes.io/part-of: mqtt
        app.kubernetes.io/instance: mosquitto
    spec:
      containers:
      - name: mosquitto
        image: eclipse-mosquitto:2.0
        ports:
        - containerPort: 1883
          name: mqtt
        volumeMounts:
        - name: config
          mountPath: /mosquitto/config
        - name: data
          mountPath: /mosquitto/data
        startupProbe:
          tcpSocket:
            port: mqtt
          timeoutSeconds: 5
          failureThreshold: 120
        readinessProbe:
          tcpSocket:
            port: mqtt
          timeoutSeconds: 5
          failureThreshold: 10
        livenessProbe:
          tcpSocket:
            port: mqtt
          failureThreshold: 3
      volumes:
      - name: config
        configMap:
          name: mosquitto-config
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ ReadWriteOnce ]
      resources:
        requests:
          storage: 1Gi
