apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: csi
spec:
  interval: 5m
  chartRef:
    kind: OCIRepository
    name: csi
  values:
    node:
      nodeSelector:
        topology.kubernetes.io/region: thuis-svc
    nodeSelector:
      node-role.kubernetes.io/control-plane: ""
    tolerations:
    - key: node-role.kubernetes.io/control-plane
      effect: NoSchedule
      operator: Exists
    existingConfigSecret: proxmox-csi
    storageClass:
    - name: proxmox-zfs-nvme
      storage: local-zfs
      reclaimPolicy: Delete
      fstype: xfs
      ssd: true
      mountOptions:
      - discard
    - name: proxmox-local-zfs
      storage: local-zfs
      reclaimPolicy: Delete
      fstype: xfs
