---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: evcc-db
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-nvme
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: evcc-config
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-nvme
  resources:
    requests:
      storage: 1Gi