apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-ntfy
  labels:
    app.kubernetes.io/instance: alertmanager-ntfy
    app.kubernetes.io/name: alertmanager-ntfy
data:
  config.yml: |-
    http:
      addr: :8000
    ntfy:
      baseurl: http://ntfy-ntfy
      notification:
        topic: alertmanager
        priority: |
          status == "firing" && labels.severity == "critical" ? "urgent" : "default"
        tags:
          - tag: white_check_mark
            condition: status == "resolved"
          - tag: rotating_light
            condition: status == "firing"
          - tag: fire_engine
            condition: labels.severity == "critical"
          - tag: snail
            condition: labels.severity == "warning"
        templates:
          title: |
            {{ if eq .Status "resolved" }}Resolved: {{ end }}{{ index .Annotations "summary" }}
          description: |
            Alert: {{ .Labels.alertname }}
            Severity: {{ .Labels.severity }}
            Starts at: {{ .StartsAt }}
            Ends at: {{ .EndsAt }}
            
            {{ .Annotations.description }}
          headers:
            X-Actions: view, Source, {{ .GeneratorURL }}
      async: false  
        
