apiVersion: v1
kind: Secret
metadata:
    name: alertmanager-ntfy
    labels:
        app.kubernetes.io/instance: alertmanager-ntfy
        app.kubernetes.io/name: alertmanager-ntfy
stringData:
    auth.yml: ENC[AES256_GCM,data:0RJiC6CHWGvaIMuz2scyAUjbolFOQzs6UisY/jHDOvfnts9vAA/PV3GP9SGvocQ+ILhEbhINMJao/qoceW0TaXdxu6PaYENG38CCuDG34FbbuxAzHDkP/VXXZg+cTOSCQuPM8gxPNupJnNPHyhLPSNcmCffd+tqrz4YXuNnfteB58D73XeWbotTWBO/t+fpZsQ==,iv:0+hXWfMOycmJjL8y3cRjjwnZTtpMz0VhqJvugRTgq0w=,tag:uIU2jXq3S9JNWWi2wSYIfg==,type:str]
sops:
    lastmodified: "2026-07-02T08:50:26Z"
    mac: ENC[AES256_GCM,data:BSuNKRVfJXqvxbc047p8B1cx1xFnx0dz/USv5pp8AwPbJtdUdrZnyJCNTzhztiQH4eX7acwnzySqh2/6CMaRDk1iaPOeG8H5P8bP0ohf0krcS2m8nA5dehHCNjjZnEPZIwQhYEhS91nHDQ2K1y59txSvBB8ToaapSJDm8k62IS4=,iv:IcJfQT2If4VEoLWv7lJokWnedEAFH4DCFBLoQoYNenM=,tag:73NXEA6FuovhqTV124X79Q==,type:str]
    pgp:
        - created_at: "2026-06-29T13:01:35Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA59YQxrIsWI6AQ/9GtgCjSflU3oFhEXZyI3omgFhhZoaiHVxdd9AbmKnAOvR
            5HnNnwFAvDpmrwgqLdC/YyO/DLuOS71Bp4L74lAwdV4dE+Hm54UAHknG2XIVt71Z
            baXdpzJ3MUK8ARCOACdDbAC5Aq7EkLFhfgYq76eiUwbMX7rnaxdQbm1bkTe24hr8
            uJJexLF7iNd0pMyzPE8kFszupqOnWi+91LnM1geYUSxR664mBSmY48Qu2025cpM/
            BLZQs8Iaiqogwpd/rJSTIBpiz5M+x4pvuwZqQ96aP57mgLm4zBQo/FpHUzsixX7h
            kzVzCFAahlshdTW4gvkSw3622aSG0F/hfBpIcAm2Vp7RPCYJqYWScyGmKSRCmw1O
            iZlRgYsveF03FEp1bppRmy2lxl5GvR0F9Y/mPc4fL3DYUTIEEkkkQNV5eeoy7jze
            HMMJkDjA0oSuR8hqxgE2+385E0DT+BSkIUgDOu+COS0MGceLLc26J50sf7fwXsZG
            ZLa7i9bqXamnhyRDaZD0ApYO3ZC/1DVsjql8hbeb5LMdaEEFyEO4dW+Tl9l0eNwg
            3yacx058I26BOgwuop1ZtP0Sn4Ohpj86UrOyB8MboL3CazcBenFSU7tx2lajyDW/
            PINxi6fxzxkcMwaAv0DJY0AIa7nUNPmmEzls2j89yhGAZECB2d79A586KRFsls3S
            XgH7zFT2951gaTiOJslEn9IEbnBcn/oJ3oUGlKgxOTbKCNwW/0alE6ION3kRDeES
            1U5/RyvPTGYSnGLORK3hKtcI64Go7MVFqG3cxhbgadKVK46mPkBG6ES7Zm69OVw=
            =dLfk
            -----END PGP MESSAGE-----
          fp: 4D72B62BB844B05E12DEC3A9A3AEC49250A67E2A
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
