apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: node-feature-discovery
  namespace: kube-system
spec:
  interval: 5m
  chart:
    spec:
      chart: node-feature-discovery
      version: 0.10.0
      sourceRef:
        kind: HelmRepository
        name: node-feature-discovery
        namespace: flux-system
  values:
    image:
      repository: docker.io/jonkerj/node-feature-discovery
      tag: v0.10.0-minimal
    worker:
      config:
        sources:
          usb:
            deviceLabelFields:
            - "vendor"
            - "device"
            - "serial"
      tolerations:
      - effect: NoSchedule
        key: efgh.nl/location
        value: gangkast
