apiVersion: monitoring.coreos.com/v1
kind: Alertmanager
metadata:
  name: alertmanager
  namespace: monitoring
spec:
  externalUrl: https://alertmanager.9ka.nl/
  configSecret: alertmanager-config
  configMaps:
  - alertmanager-templates
  storage:
    volumeClaimTemplate:
      spec:
        storageClassName: proxmox-zfs-nvme
        resources:
          requests:
            storage: 1Gi
  resources:
    requests:
      cpu: 50m
      memory: 100Mi
    limits:
      cpu: 750m
      memory: 250Mi
