apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus
spec:
  retention: 8w
  serviceMonitorSelector: {}
  serviceMonitorNamespaceSelector: {}
  podMonitorSelector: {}
  podMonitorNamespaceSelector: {}
  ruleNamespaceSelector: {}
  ruleSelector: {}
  serviceAccountName: prometheus
  externalUrl: https://prometheus.9ka.nl
  alerting:
    alertmanagers:
    - namespace: monitoring
      name: alertmanager-operated
      port: web
      apiVersion: v2
  storage:
    volumeClaimTemplate:
      spec:
        storageClassName: proxmox-zfs-nvme
        resources:
          requests:
            storage: 40Gi
  resources:
    requests:
      memory: 1Gi
      cpu: 500m
    limits:
      memory: 2Gi
      cpu: 2000m
