apiVersion: v1
data:
    alertmanager.yaml: ENC[AES256_GCM,data:J76Vz9FuBVhctE7IuYbldwC7BcqTF3zvGN8GO32ddys/KKvonqIuweaKMfj9+nzwDxKMACVJ3jwLMVc2v/OM2j7UP8N5qAA1+TyDet3eS1EXscBPvgBMyaQ2Um3DLru48b2chPCo9FkL/+zL8T4j9Zp1XP9jp7nrSD02MM+NdaARBsmRglRnxSTK6eAZuJyFpdkMDnQCBAnH6+yG9wzxKlhBfiLk7NthKlcvLAs/EGLrvwxJn7m9ip8SyGPA/hV0gIRhY1xIH4/XqrS6oVIH+bbR2zdGq/BftHErvtg83/t8EUCEX4cIq+HICR5v/pSzzwF1hgqvanXRsJ4UI8JYRW+04SMJZpUYRaHE9P8UQY/vP9km4OvbTkI2GzQgQq4YRaDp9NX+H3kN/Dtqhs73U4Gni1FBbHJDqQurZmUMh90mOKFH1hY6KwQ+hG87Cp9fzs4FLFJwKl01Y2/G4LFayhY8cPRiD/IeJGY7p+QtjX8YR0TEUlDGurdebdZyWATi,iv:zNwVxC3bbAj3CO5U8pq/A2iz8+pou57igFKL/s2O7Aw=,tag:5ErsN+t62WlGP7E+TAlBOA==,type:str]
kind: Secret
metadata:
    name: alertmanager-config
type: Opaque
sops:
    lastmodified: "2026-06-29T13:14:11Z"
    mac: ENC[AES256_GCM,data:gRrkdu7N8WeVZmmLp9wLsbWBE8VavD47IuOpS4ynA40TYdMXndgSHmYVGe+SoeC5OpLF3y30CrCFyYfCmL6xA4jyjyHTaheIuCt4AYHBj2P88jaHh/Fv0QvlECeyCLhSQuA7NkY03zNNLN3wdJx4OO0gRmiyDU7GYvofepyiugc=,iv:C7y+2o72d2jAiuSTmdnetKLC2KeHPyjXXTa77jIO0oU=,tag:M6g82Ss6ipyr6281Hb9cKg==,type:str]
    pgp:
        - created_at: "2021-02-22T18:54:50Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA59YQxrIsWI6ARAAhSHjZVj/Lrn98rOz0Eg7doH0z/ixzCATo7rctWeqYx+H
            8WgmvBA2MegPPpQitY4gamqfvt7AhNBGaNIgZ3DQVqrHXNTtqN/YmlmXvH1+C6d0
            vALFmr87co6hqjAEwQVsz5Ro/DMWVmIFxdgFSrB8WpEc8q2cSSNs50PEr94ZIYGq
            Fr1uXGxAQ6VnTUULSGh77SD1cYtj3+K34konBLsT7PVwEGoAEbEHegKgcH1BVARE
            EsHkJ8KM8JFB0FIj1AFokHH/8nO4Np1/gIiU0RyAJCRwEAOgGsP9lIlCdKukFgT4
            fJwUDEeCpcYWu1FpT2iplLZ/d+wixYY1eED+rBmVIiD5mAD7C876q4SteUJhlC0F
            w1c6LENw6Mho0quVymaIhYjx+s8MD3M7ReZpe0Lvxa1HeibhMCQobXTm55H+2B21
            QKrfYIknifZeR/ALVehBPVf1xdwgcWLzf9oY3sXXrUbqas2rAGGB4KbpENAnbOxb
            II5sQ0Bqh1VgM2StP4lXmOJS9JPSHC4ZfEh812wAltMDw5zjl9Zlo0hrNL67QCiG
            G/oL283PQT3NX3Nysvv5mvufBaYCLmCLxibPwXNH1kElTd6KjBVaFRf9y1kirBme
            GclVtnzkcZMIjDB1RfzigITLhubXKSscFqBYzYqNrO1+iXQkpQTXkHNvcEflHf/S
            XAEXlSx0iMzYw6bcmJyC2Fy0fAbpkOSB0g1wa8DVClj3lMqnAykNOe6b32r7kHbM
            TNlQOTz8RNMqBjrYMVLzNCDyvk1fki11OaIEiTG40cdrXxBewSObflxf97gd
            =l4qZ
            -----END PGP MESSAGE-----
          fp: 4D72B62BB844B05E12DEC3A9A3AEC49250A67E2A
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
