apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nextcloud
  namespace: nextcloud
spec:
  interval: 5m
  upgrade:
    remediation:
      retries: 10
  chart:
    spec:
      chart: nextcloud
      version: 6.6.2
      sourceRef:
        kind: HelmRepository
        name: nextcloud
        namespace: flux-system
  values:
    ingress:
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt
        nginx.ingress.kubernetes.io/proxy-body-size: 32m
      enabled: true
      tls:
      - secretName: nextcloud-tls
        hosts:
        - nc.9ka.nl
    nextcloud:
      configs:
        extra.config.php: |-
          <?php
            $CONFIG = array(
              'overwriteprotocol' => 'https',
            );
          ?>
      host: nc.9ka.nl
      password: null
    persistence:
      enabled: true
      size: 25Gi
    startupProbe:
      enabled: true
      failureThreshold: 360
    resources:
      requests:
        cpu: 100m
        memory: 768Mi
      limits:
        cpu: 2000m
        memory: 2048Mi
