apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nextcloud
spec:
  interval: 5m
  upgrade:
    remediation:
      retries: 10
  chart:
    spec:
      chart: nextcloud
      version: 8.4.0
      sourceRef:
        kind: HelmRepository
        name: nextcloud
  values:
    ingress:
      annotations:
        external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
        external-dns.alpha.kubernetes.io/hostname: nextcloud.9ka.nl
        external-dns.alpha.kubernetes.io/target: 431113a6-4cf3-4a66-9750-17113ae2e689.cfargotunnel.com
        nginx.ingress.kubernetes.io/proxy-body-size: 32m
      className: cilium
      enabled: true
    nextcloud:
      configs:
        extra.config.php: |-
          <?php
            $CONFIG = array(
              'overwriteprotocol' => 'https',
            );
          ?>
      host: nc.9ka.nl
      password: null
    persistence:
      enabled: true
      existingClaim: nextcloud-data
    startupProbe:
      enabled: true
      failureThreshold: 360
    resources:
      requests:
        cpu: 100m
        memory: 768Mi
      limits:
        cpu: 2000m
        memory: 2048Mi
