apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud
  namespace: nextcloud
  labels:
    app.kubernetes.io/name: nextcloud
spec:
  storageClassName: proxmox-local-zfs
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
