apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-data
  labels:
    app.kubernetes.io/name: nextcloud
spec:
  storageClassName: proxmox-zfs-nvme
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
