apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: node-feature-discovery
  namespace: node-feature-discovery
spec:
  interval: 5m
  chart:
    spec:
      chart: node-feature-discovery
      version: 0.17.3
      sourceRef:
        kind: HelmRepository
        name: node-feature-discovery
  values:
    enableNodeFeatureApi: false
    worker:
      config:
        sources:
          usb:
            deviceLabelFields:
            - "vendor"
            - "device"
            - "serial"
      tolerations:
      - effect: NoSchedule
        key: efgh.nl/location
        value: gangkast
        operator: Equal
      - effect: NoSchedule
        key: efgh.nl/location
        value: zolder
        operator: Equal
    master:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: topology.kubernetes.io/region
                operator: In
                values:
                - thuis-svc
      tolerations:
      - operator: Equal
        key: efgh.nl/location
        value: zolder
        effect: NoSchedule
    gc:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: topology.kubernetes.io/region
                operator: In
                values:
                - thuis-svc
      tolerations:
      - operator: Equal
        key: efgh.nl/location
        value: zolder
        effect: NoSchedule
