apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: node-feature-discovery
spec:
  interval: 5m
  chart:
    spec:
      chart: node-feature-discovery
      version: 0.17.4
      sourceRef:
        kind: HelmRepository
        name: node-feature-discovery
  values:
    enableNodeFeatureApi: false
    worker:
      config:
        sources:
          usb:
            deviceLabelFields:
            - "vendor"
            - "device"
            - "serial"
