apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: node-feature-discovery
spec:
  interval: 5m
  chart:
    spec:
      chart: node-feature-discovery
      version: 0.18.3
      sourceRef:
        kind: HelmRepository
        name: node-feature-discovery
  values:
    enableNodeFeatureApi: false
    worker:
      tolerations:
      - effect: NoSchedule
        key: efgh.nl/location
        value: gangkast
      config:
        core:
          labelSources:
          - usb
        sources:
          usb:
            deviceLabelFields:
            - "vendor"
            - "device"
            - "serial"
