apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: node-feature-discovery
spec:
  interval: 5m
  chart:
    spec:
      chart: node-feature-discovery
      version: 0.18.3
      sourceRef:
        kind: HelmRepository
        name: node-feature-discovery
  values:
    enableNodeFeatureApi: false
    gc:
      resources:
        requests:
          cpu: 60m
          memory: 12Mi
        limits:
          cpu: 500m
          memory: 128Mi
    master:
      resources:
        requests:
          cpu: 60m
          memory: 72Mi
        limits:
          cpu: 500m
          memory: 128Mi
    worker:
      resources:
        requests:
          cpu: 25m
          memory: 64Mi
        limits:
          cpu: 500m
          memory: 128Mi
      tolerations:
      - effect: NoSchedule
        key: efgh.nl/location
        value: gangkast
      config:
        core:
          labelSources:
          - usb
        sources:
          usb:
            deviceClassWhitelist:
            - "00" # use interface class <- this one is not default
            - "01" # audio <- this one is not default
            - "0e" # video
            - "ef" # misc
            - "fe" # application specific
            - "ff" # vendor specific
