apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: node-feature-discovery
  namespace: node-feature-discovery
spec:
  interval: 5m
  chart:
    spec:
      chart: node-feature-discovery
      version: 0.16.6
      sourceRef:
        kind: HelmRepository
        name: node-feature-discovery
  values:
    enableNodeFeatureApi: false
    worker:
      config:
        sources:
          usb:
            deviceLabelFields:
            - "vendor"
            - "device"
            - "serial"
      tolerations:
      - effect: NoSchedule
        key: efgh.nl/location
        value: gangkast
