---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: descheduler
  namespace: flux-system
spec:
  url: https://kubernetes-sigs.github.io/descheduler/
  interval: 1h
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: jonkerj
  namespace: flux-system
spec:
  url: https://jonkerj.github.io/charts/
  interval: 1h
