apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- flux-components.yaml
- flux-sync.yaml
- flux-monitoring.yaml
- efgh-sync.yaml
- webhooks.yaml
patchesStrategicMerge:
- flux-resources.yaml
- flux-thuis-svc.yaml
