apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: oauth2-proxy
  namespace: oauth2-proxy
spec:
  interval: 5m
  chart:
    spec:
      chart: oauth2-proxy
      version: 7.1.0
      sourceRef:
        kind: HelmRepository
        name: oauth2-proxy
        namespace: flux-system
  values:
    config:
      existingSecret: oauth2-secret
    extraArgs:
      email-domain: "kippendief.biz"
      oidc-issuer-url: "https://dex.9ka.nl"
      provider: "oidc"
      set-authorization-header: "true"
      show-debug-on-error: "true"
      skip-provider-button: "true"
      whitelist-domain: ".9ka.nl"
#    ingress:
#      enabled: false
#      path: /oauth2
#      hosts:
#      - prometheus.9ka.nl
#      - alertmanager.9ka.nl
#      annotations:
#        nginx.ingress.kubernetes.io/proxy-buffer-size: 64k
    resources:
      requests:
        cpu: 50m
        memory: 8Mi
      limits:
        cpu: 250m
        memory: 64Mi
