apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: oauth2-proxy
  namespace: oauth2-proxy
spec:
  interval: 5m
  chart:
    spec:
      chart: oauth2-proxy
      version: 3.3.2
      sourceRef:
        kind: HelmRepository
        name: oauth2-proxy
        namespace: flux-system
  values:
    config:
      existingSecret: oauth2-secret
    extraArgs:
      email-domain: "kippendief.biz"
      oidc-issuer-url: "https://sso.9ka.nl/auth/realms/9ka"
      provider: "oidc"
      set-authorization-header: "true"
      show-debug-on-error: "true"
      skip-provider-button: "true"
      whitelist-domain: ".9ka.nl"
    ingress:
      enabled: true
      path: /oauth2
      hosts:
      - prometheus.9ka.nl
      - alertmanager.9ka.nl
      - dashboard.9ka.nl
      - hubble.9ka.nl
      annotations:
        nginx.ingress.kubernetes.io/proxy-buffer-size: 64k
    resources:
      requests:
        cpu: 50m
        memory: 8Mi
      limits:
        cpu: 250m
        memory: 64Mi
