apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  interval: 5m
  chart:
    spec:
      chart: cert-manager
      version: v1.4.0
      sourceRef:
        kind: HelmRepository
        name: jetstack
        namespace: flux-system
  values:
    prometheus:
      servicemonitor:
        enabled: true
        labels:
          release: monitoring
    resources:
      requests:
        cpu: 50m
        memory: 100Mi
      limits:
        cpu: 250m
        memory: 250Mi
    cainjector:
      resources:
        requests:
          cpu: 50m
          memory: 90Mi
        limits:
          cpu: 250m
          memory: 250Mi
    webhook:
      resources:
        requests:
          cpu: 50m
          memory: 50Mi
        limits:
          cpu: 250m
          memory: 100Mi
