apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: velero
  namespace: velero
spec:
  interval: 5m
  chart:
    spec:
      chart: velero
      version: 2.28.0
      sourceRef:
        kind: HelmRepository
        name: vmware-tanzu
        namespace: flux-system
  values:
    deployRestic: false
    snapshotsEnabled: false
    configuration:
      provider: aws
      backupStorageLocation:
        provider: aws
        bucket: velero
        config:
          publicUrl: http://neon.thuis.efgh.nl:9000
          region: minio
          s3ForcePathStyle: "true"
          s3Url: http://neon.thuis.efgh.nl:9000
    credentials:
      useSecret: false
      extraSecretRef: velero-env-vars
    schedules:
      backup:
        schedule: '@every 24h'
        template:
          ttl: 732h
          includeClusterResources: true
    initContainers:
    - name: velero-plugin-for-aws
      image: velero/velero-plugin-for-aws:v1.4.0
      imagePullPolicy: IfNotPresent
      volumeMounts:
      - mountPath: /target
        name: plugins
    metrics:
      enabled: true
      scrapeInterval: 1m
      serviceMonitor:
        enabled: true
