{
 "title": "Energiebalans",
 "time": { "from": "now/M", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "location",
    "query": "from(bucket: \"nuts\")\n|> range(start: v.timeRangeStart)\n|> keyValues(keyColumns: [\"location\"])\n|> group()\n|> keep(columns: [\"location\"])\n|> distinct(column: \"location\")"
   }
  ]
 },
 "panels": [
  {
   "title": "Delivered T1",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"nuts\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"power\" and r[\"_field\"] == \"electricity_delivered_tariff_1\" and r[\"location\"] == \"${location}\")\n  |> aggregateWindow(every: v.windowPeriod, fn:last)\n  |> drop(columns: [\"location\"])\n  |> map(fn: (r) => ({ r with _value: r._value / 3600.0 }))\n  |> increase()\n  |> yield(name: \"nuts\")"
    }
   ]
  },
  {
   "title": "Used T1",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"nuts\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"power\" and r[\"_field\"] == \"electricity_used_tariff_1\" and r[\"location\"] == \"${location}\")\n  |> aggregateWindow(every: v.windowPeriod, fn:last)\n  |> drop(columns: [\"location\"])\n  |> increase()\n  |> map(fn: (r) => ({ r with _value: r._value / -3600.0 }))\n  |> yield(name: \"nuts\")"
    }
   ]
  },
  {
   "title": "Saldo T1",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"nuts\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"power\" and r[\"_field\"] =~ /electricity_.*_tariff_1/ and r[\"location\"] == \"${location}\")\n  |> aggregateWindow(every: v.windowPeriod, fn:last)\n  |> drop(columns: [\"location\"])\n  |> increase()\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> map(fn: (r) => ({ r with _value: (r[\"electricity_delivered_tariff_1\"]-r[\"electricity_used_tariff_1\"]) / 3600.0 }))\n  |> keep(columns: [\"_time\", \"_value\"])\n  |> yield(name: \"nuts\")"
    }
   ]
  },
  {
   "title": "Saldo",
   "type": "stat",
   "gridPos": { "h": 14, "w": 7, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"nuts\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"power\" and r[\"_field\"] =~ /electricity_(used|delivered)_tariff_./ and r[\"location\"] == \"${location}\")\n  |> aggregateWindow(every: v.windowPeriod, fn:last)\n  |> drop(columns: [\"location\"])\n  |> increase()\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> map(fn: (r) => ({ r with _value: (r[\"electricity_delivered_tariff_1\"]+r[\"electricity_delivered_tariff_2\"]-r[\"electricity_used_tariff_1\"]-r[\"electricity_used_tariff_2\"]) / 3600.0 }))\n  |> keep(columns: [\"_time\", \"_value\"])\n  |> yield(name: \"nuts\")"
    }
   ]
  },
  {
   "title": "Delivered T2",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"nuts\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"power\" and r[\"_field\"] == \"electricity_delivered_tariff_2\" and r[\"location\"] == \"${location}\")\n  |> aggregateWindow(every: v.windowPeriod, fn:last)\n  |> drop(columns: [\"location\"])\n  |> map(fn: (r) => ({ r with _value: r._value / 3600.0 }))\n  |> increase()\n  |> yield(name: \"nuts\")"
    }
   ]
  },
  {
   "title": "Used T2",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"nuts\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"power\" and r[\"_field\"] == \"electricity_used_tariff_2\" and r[\"location\"] == \"${location}\")\n  |> aggregateWindow(every: v.windowPeriod, fn:last)\n  |> drop(columns: [\"location\"])\n  |> increase()\n  |> map(fn: (r) => ({ r with _value: r._value / -3600.0 }))\n  |> yield(name: \"nuts\")"
    }
   ]
  },
  {
   "title": "Saldo T2",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"nuts\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"power\" and r[\"_field\"] =~ /electricity_.*_tariff_2/ and r[\"location\"] == \"${location}\")\n  |> aggregateWindow(every: v.windowPeriod, fn:last)\n  |> drop(columns: [\"location\"])\n  |> increase()\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> map(fn: (r) => ({ r with _value: (r[\"electricity_delivered_tariff_2\"]-r[\"electricity_used_tariff_2\"]) / 3600.0 }))\n  |> keep(columns: [\"_time\", \"_value\"])\n  |> yield(name: \"nuts\")"
    }
   ]
  },
  {
   "title": "PV Yield",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"solar\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"sma\" and r[\"_field\"] == \"ac_total_yield\" and r[\"location\"] == \"${location}\")\n  |> aggregateWindow(every: v.windowPeriod, fn:last)\n  |> drop(columns: [\"location\"])\n  |> map(fn: (r) => ({ r with _value: r._value / 3600.0 }))\n  |> increase()\n  |> yield(name: \"nuts\")"
    }
   ]
  },
  {
   "title": "District heat",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 8, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "joule" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"nuts\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"heat\" and r[\"_field\"] == \"energy\" and r[\"location\"] == \"${location}\")\n  |> aggregateWindow(every: v.windowPeriod, fn:last)\n  |> drop(columns: [\"location\"])\n  |> increase()\n  |> yield(name: \"nuts\")"
    }
   ]
  }
 ]
}