{
 "title": "NFSd",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "node_name",
    "query": "label_values(node_nfsd_requests_total, node_name)"
   }
  ]
 },
 "panels": [
  {
   "title": "Requests",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum by (method) (irate(node_nfsd_requests_total{node_name=\"$node_name\"}[2m]))",
     "legendFormat": "{{ method }}"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_nfsd_connections_total{node_name=\"$node_name\"}",
     "legendFormat": "tcp"
    }
   ]
  },
  {
   "title": "Disk IO",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "binBps" }
   ],
   "targets": [
    {
     "expr": "irate(node_nfsd_disk_bytes_read_total{node_name=\"$node_name\"}[2m])",
     "legendFormat": "read"
    },
    {
     "expr": "irate(node_nfsd_disk_bytes_written_total{node_name=\"$node_name\"}[2m])",
     "legendFormat": "written"
    }
   ]
  }
 ]
}