{
 "title": "PowerDNS recursor",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "node",
    "query": {
     "query": "label_values(pdns_recursor_uptime, node_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "DNSSEC Validation",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "irate(pdns_recursor_dnssec_result_secure{node_name=\"$node\"}[10m])",
     "legendFormat": "secure"
    },
    {
     "expr": "irate(pdns_recursor_dnssec_result_insecure{node_name=\"$node\"}[10m])",
     "legendFormat": "insecure"
    },
    {
     "expr": "irate(pdns_recursor_dnssec_result_nta{job=\"$job\"}[10m])",
     "legendFormat": "nta"
    },
    {
     "expr": "irate(pdns_recursor_dnssec_result_indeterminate{job=\"$job\"}[10m])",
     "legendFormat": "indeterminate"
    },
    {
     "expr": "irate(pdns_recursor_dnssec_result_bogus{job=\"$job\"}[10m])",
     "legendFormat": "bogus"
    }
   ]
  },
  {
   "title": "Outgoing queries",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "irate(pdns_recursor_all_outqueries{node_name=\"$node\"}[10m])",
     "legendFormat": "All"
    },
    {
     "expr": "irate(pdns_recursor_tcp_outqueries{node_name=\"$node\"}[10m])",
     "legendFormat": "TCP"
    },
    {
     "expr": "irate(pdns_recursor_outgoing4_timeouts{node_name=\"$node\"}[10m])",
     "legendFormat": "IPv4 timeout"
    },
    {
     "expr": "irate(pdns_recursor_outgoing6_timeouts{node_name=\"$node\"}[10m])",
     "legendFormat": "IPv6 timeout"
    },
    {
     "expr": "irate(pdns_recursor_throttled_out{node_name=\"$node\"}[10m])",
     "legendFormat": "Throttled"
    }
   ]
  },
  {
   "title": "Cache",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "irate(pdns_recursor_cache_hits{node_name=\"$node\"}[10m])",
     "legendFormat": "hits"
    },
    {
     "expr": "irate(pdns_recursor_cache_misses{node_name=\"$node\"}[10m])",
     "legendFormat": "misses"
    },
    {
     "expr": "pdns_recursor_cache_entries{node_name=\"$node\"}",
     "legendFormat": "entries"
    }
   ]
  },
  {
   "title": "Incoming queries",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "irate(pdns_recursor_over_capacity_drops{node_name=\"$node\"}[10m])",
     "legendFormat": "capacity drops"
    },
    {
     "expr": "irate(pdns_recursor_policy_drops{node_name=\"$node\"}[10m])",
     "legendFormat": "policy drops"
    },
    {
     "expr": "irate(pdns_recursor_packetcache_hits{node_name=\"$node\"}[10m])",
     "legendFormat": "packet cache"
    },
    {
     "expr": "irate(pdns_recursor_answers0_1{node_name=\"$node\"}[10m])",
     "legendFormat": "< 1ms"
    },
    {
     "expr": "irate(pdns_recursor_answers1_10{node_name=\"$node\"}[10m])",
     "legendFormat": "1 - 10ms"
    },
    {
     "expr": "irate(pdns_recursor_answers10_100{node_name=\"$node\"}[10m])",
     "legendFormat": "10 - 100ms"
    },
    {
     "expr": "irate(pdns_recursor_answers100_1000{node_name=\"$node\"}[10m])",
     "legendFormat": "100 - 1000ms"
    },
    {
     "expr": "irate(pdns_recursor_answers_slow{node_name=\"$node\"}[10m])",
     "legendFormat": "> 1000ms"
    }
   ]
  }
 ]
}