{
 "title": "Solar",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "location",
    "query": "from(bucket: \"solar\")\n|> range(start: v.timeRangeStart)\n|> keyValues(keyColumns: [\"location\"])\n|> group()\n|> keep(columns: [\"location\"])\n|> distinct(column: \"location\")"
   }
  ]
 },
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Watt per Watt-Peak",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "sma",
     "query": "from(bucket: \"solar\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"sma\" and r._field == \"ac_pv_generated_power\" and r.location == \"${location}\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: true)\n  |> drop(columns: [\"location\"])\n  |> map(fn: (r) => ({ r with _value: r._value /5360.0 }))\n  |> yield(name: \"power\")",
     "select": [
      [
       { "params": [ "ac_pv_generated_power" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 5360" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Solar Power",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "sma",
     "query": "from(bucket: \"solar\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"sma\" and r._field == \"ac_power\" and r.location == \"${location}\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: true)\n  |> drop(columns: [\"location\"])\n  |> yield(name: \"power\")",
     "select": [
      [
       { "params": [ "ac_power" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Sun Azimuth",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "target": "sun_azimuth" }
   ]
  },
  {
   "title": "Sun Altitude",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "target": "sun_altitude" }
   ]
  },
  { "title": "AC Side", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Grid Frequency",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "hertz" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "sma",
     "query": "from(bucket: \"solar\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"sma\" and r._field == \"ac_grid_frequency\" and r.location == \"${location}\")\n  |> drop(columns: [\"location\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: true)\n  |> yield(name: \"power\")",
     "select": [
      [
       { "params": [ "ac_grid_frequency" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Grid voltage",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "L1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "sma",
     "query": "from(bucket: \"solar\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"sma\" and r._field == \"ac_phase_voltage_l1\" and r.location == \"${location}\")\n  |> drop(columns: [\"location\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: true)\n  |> yield(name: \"power\")",
     "select": [
      [
       { "params": [ "ac_phase_voltage_l1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Yield",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"solar\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"sma\" and r._field == \"ac_total_yield\" and r.location == \"${location}\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: true)\n  |> drop(columns: [\"location\"])\n  |> increase()\n  |> map(fn: (r) => ({ r with _value: r._value /3600.0 }))\n  |> yield(name: \"power\")"
    }
   ]
  },
  {
   "title": "Daily yield",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "yield",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "sma",
     "query": "from(bucket: \"solar\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"sma\" and r._field == \"ac_daily_yield\" and r.location == \"${location}\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: true)\n  |> drop(columns: [\"location\"])\n  |> map(fn: (r) => ({ r with _value: r._value /3600.0 }))\n  |> yield(name: \"power\")",
     "select": [
      [
       { "params": [ "ac_daily_yield" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 3600" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "AC Power",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "alias": "L1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "sma",
     "query": "import \"strings\"\n\nfrom(bucket: \"solar\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"sma\" and r._field =~ /ac_active_power_l./ and r.location == \"${location}\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: true)\n  |> drop(columns: [\"location\"])\n  |> map(fn: (r) => ({ r with _field: \"L\" + strings.replaceAll(v: r._field, t: \"ac_active_power_l\", u: \"\") }))\n  |> yield(name: \"power\")",
     "select": [
      [
       { "params": [ "ac_active_power_l1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "AC Current",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "L1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "sma",
     "query": "import \"strings\"\nfrom(bucket: \"solar\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"sma\" and r._field =~ /ac_phase_current_l./ and r.location == \"${location}\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: true)\n  |> drop(columns: [\"location\"])\n  |> map(fn: (r) => ({ r with _field: \"L\" + strings.replaceAll(v: r._field, t: \"ac_phase_current_l\", u: \"\")}))\n  |> yield(name: \"power\")",
     "select": [
      [
       { "params": [ "ac_phase_current_l1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "AC Phase voltages",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "alias": "L1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "sma",
     "query": "import \"strings\"\nfrom(bucket: \"solar\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"sma\" and r._field =~ /^ac_phase_voltage_l.$/ and r.location == \"${location}\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: true)\n  |> drop(columns: [\"location\"])\n  |> map(fn: (r) => ({ r with _field: \"L\" + strings.replaceAll(v: r._field, t: \"ac_phase_voltage_l\", u: \"\") }))\n  |> yield(name: \"power\")",
     "select": [
      [
       { "params": [ "ac_phase_voltage_l1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "AC Inter phase voltages",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "alias": "L1-L2",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "sma",
     "query": "import \"strings\"\nfrom(bucket: \"solar\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"sma\" and r._field =~ /^ac_phase_voltage_l._l.$/ and r.location == \"${location}\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: true)\n  |> drop(columns: [\"location\"])\n  |> map(fn: (r) => ({ r with _field: strings.replaceAll(v: r._field, t: \"ac_phase_voltage_\", u: \"\"), _value: r._value }))\n  |> yield(name: \"power\")",
     "select": [
      [
       { "params": [ "ac_phase_voltage_l1_l2" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "DC Side", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 } },
  {
   "title": "DC Power",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "alias": "A",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "sma",
     "query": "import \"strings\"\nfrom(bucket: \"solar\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"sma\" and r._field =~ /dc_power_/ and r.location == \"${location}\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: true)\n  |> drop(columns: [\"location\"])\n  |> map(fn: (r) => ({ r with _field: strings.replaceAll(v: r._field, t: \"dc_power_\", u: \"\"), _value: r._value }))\n  |> yield(name: \"power\")",
     "select": [
      [
       { "params": [ "dc_power_a" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "B",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "sma",
     "select": [
      [
       { "params": [ "dc_power_b" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "DC Power per panel",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "alias": "A (400Wp)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "sma",
     "query": "import \"strings\"\n\nfrom(bucket: \"solar\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"sma\" and r._field == \"dc_power_a\" and r.location == \"${location}\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: true)\n  |> map(fn: (r) => ({ r with _value: r._value / 6.0, _field: \"A\"}))\n  |> drop(columns: [\"location\"])\n  |> drop(columns: [\"location\"])\n  |> yield(name: \"A\")",
     "select": [
      [
       { "params": [ "dc_power_a" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 6" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "B (370Wp)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "sma",
     "query": "from(bucket: \"solar\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"sma\" and r._field == \"dc_power_b\" and r.location == \"${location}\")\n  |> map(fn: (r) => ({ r with _value: r._value / 8.0, _field: \"B\"}))\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: true)\n  |> drop(columns: [\"location\"])\n  |> yield(name: \"B\")",
     "select": [
      [
       { "params": [ "dc_power_b" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 8" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "DC Voltage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "alias": "A",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "sma",
     "query": "import \"strings\"\nfrom(bucket: \"solar\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"sma\" and r._field =~ /dc_voltage_/ and r.location == \"${location}\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: true)\n  |> drop(columns: [\"location\"])\n  |> map(fn: (r) => ({ r with _field: strings.replaceAll(v: r._field, t: \"dc_voltage_\", u: \"\"), _value: r._value }))\n  |> drop(columns: [\"location\"])\n  |> yield(name: \"voltage\")",
     "select": [
      [
       { "params": [ "dc_voltage_a" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "B",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "sma",
     "select": [
      [
       { "params": [ "dc_voltage_b" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "DC Current",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    {
     "alias": "A",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "sma",
     "query": "import \"strings\"\nfrom(bucket: \"solar\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"sma\" and r._field =~ /dc_current_/ and r.location == \"${location}\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: true)\n  |> drop(columns: [\"location\"])\n  |> map(fn: (r) => ({ r with _field: strings.replaceAll(v: r._field, t: \"dc_current_\", u: \"\"), _value: r._value }))\n  |> drop(columns: [\"location\"])\n  |> yield(name: \"voltage\")",
     "select": [
      [
       { "params": [ "dc_current_a" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "B",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "sma",
     "select": [
      [
       { "params": [ "dc_current_b" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}