{
 "title": "System stats",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "node_name",
    "label": "node",
    "query": {
     "query": "label_values(node_boot_time_seconds, node_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (mode) (irate(node_cpu_seconds_total{node_name=\"$node_name\"}[2m]))",
     "legendFormat": "{{ mode }}"
    }
   ]
  },
  {
   "title": "Network traffic",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "targets": [
    {
     "expr": "sum by (device) (irate(node_network_receive_bytes_total{node_name=\"$node_name\", device=~\"^(eno|enp|ens|eth|isp|wlan|thuis|iot|vxlan).*$\"}[2m]))",
     "legendFormat": "RX {{ device }}"
    },
    {
     "expr": "sum by (device) (irate(node_network_transmit_bytes_total{node_name=\"$node_name\", device=~\"^(eno|enp|ens|eth|isp|wlan|thuis|iot|vxlan).*$\"}[2m]))",
     "legendFormat": "TX {{ device }}"
    }
   ]
  },
  {
   "title": "Disk IO",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "binBps" }
   ],
   "targets": [
    {
     "expr": "sum by (device) (irate(node_disk_read_bytes_total{node_name=\"$node_name\", device=~\"^([vsx]d[a-z]|mmcblk[0-9])\"}[2m]))",
     "legendFormat": "R {{ device }}"
    },
    {
     "expr": "sum by (device) (irate(node_disk_written_bytes_total{node_name=\"$node_name\", device=~\"^([vsx]d[a-z]|mmcblk[0-9])\"}[2m]))",
     "legendFormat": "W {{ device }}"
    }
   ]
  },
  {
   "title": "I/O time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (device) (irate(node_disk_io_time_seconds_total{node_name=\"$node_name\", device=~\"^([vsx]d[a-z]|mmcblk[0-9])\"}[2m]))",
     "legendFormat": "{{ mode }}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{node_name=\"$node_name\"} - node_memory_MemFree_bytes{node_name=\"$node_name\"} - node_memory_KernelStack_bytes{node_name=\"$node_name\"} - node_memory_AnonPages_bytes{node_name=\"$node_name\"} - node_memory_PageTables_bytes{node_name=\"$node_name\"} - node_memory_Slab_bytes{node_name=\"$node_name\"} - node_memory_Cached_bytes{node_name=\"$node_name\"} - node_memory_SwapCached_bytes{node_name=\"$node_name\"} - node_memory_Buffers_bytes{node_name=\"$node_name\"} - (node_memory_HugePages_Total{node_name=\"$node_name\"} * 2097152)",
     "legendFormat": "Unaccounted For"
    },
    {
     "expr": "node_memory_Buffers_bytes{node_name=\"$node_name\"}",
     "legendFormat": "Buffers"
    },
    {
     "expr": "node_memory_SwapCached_bytes{node_name=\"$node_name\"}",
     "legendFormat": "Swap Cached"
    },
    {
     "expr": "node_memory_KernelStack_bytes{node_name=\"$node_name\"}",
     "legendFormat": "Kernel Stack"
    },
    {
     "expr": "node_memory_Slab_bytes{node_name=\"$node_name\"}",
     "legendFormat": "Slab"
    },
    {
     "expr": "node_memory_PageTables_bytes{node_name=\"$node_name\"}",
     "legendFormat": "Page Tables"
    },
    {
     "expr": "node_memory_AnonPages_bytes{node_name=\"$node_name\"}",
     "legendFormat": "Anonymous"
    },
    {
     "expr": "node_memory_Shmem_bytes{node_name=\"$node_name\"}",
     "legendFormat": "Shared memory smallpages"
    },
    {
     "expr": "node_memory_Cached_bytes-node_memory_Shmem_bytes{node_name=\"$node_name\"}",
     "legendFormat": "Mapped and Cached"
    },
    {
     "expr": "node_memory_MemFree_bytes{node_name=\"$node_name\"}",
     "legendFormat": "Free"
    },
    {
     "expr": "(node_memory_HugePages_Free{node_name=\"$node_name\"}-node_memory_HugePages_Rsvd{node_name=\"$node_name\"})*2097152",
     "legendFormat": "Hugepages Free"
    },
    {
     "expr": "node_memory_HugePages_Rsvd{node_name=\"$node_name\"}*2097152",
     "legendFormat": "Hugepages Reserved"
    },
    {
     "expr": "(node_memory_HugePages_Total{node_name=\"$node_name\"}-node_memory_HugePages_Free{node_name=\"$node_name\"})*2097152",
     "legendFormat": "Hugepages Used"
    }
   ]
  }
 ]
}