{
 "title": "WiFi",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "node_name",
    "label": "node",
    "query": "label_values(wifi_stations, node_name)"
   },
   {
    "name": "ifname",
    "label": "interface",
    "query": "label_values(wifi_stations, ifname)"
   }
  ]
 },
 "panels": [
  {
   "title": "Signal",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "dBm" }
   ],
   "targets": [
    {
     "expr": "sum by (mac) (wifi_station_signal_dbm{node_name=\"$node_name\", ifname=\"$ifname\"})",
     "legendFormat": "{{ nac }}"
    }
   ]
  },
  {
   "title": "Inactive",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum by (mac) (wifi_station_inactive_milliseconds{node_name=\"$node_name\", ifname=\"$ifname\"})",
     "legendFormat": "{{ nac }}"
    }
   ]
  },
  {
   "title": "Transmit speed",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "Kbits" }
   ],
   "targets": [
    {
     "expr": "sum by (mac) (wifi_station_transmit_kilobits_per_second{node_name=\"$node_name\", ifname=\"$ifname\"})",
     "legendFormat": "{{ nac }}"
    }
   ]
  },
  {
   "title": "Receive speed",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "Kbits" }
   ],
   "targets": [
    {
     "expr": "sum by (mac) (wifi_station_receive_kilobits_per_second{node_name=\"$node_name\", ifname=\"$ifname\"})",
     "legendFormat": "{{ nac }}"
    }
   ]
  },
  {
   "title": "Packets received",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "sum by (mac) (irate(wifi_station_receive_packets_total{node_name=\"$node_name\", ifname=\"$ifname\"}[2m]))",
     "legendFormat": "{{ nac }}"
    }
   ]
  },
  {
   "title": "Packets transmitted",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "sum by (mac) (irate(wifi_station_transmit_packets_total{node_name=\"$node_name\", ifname=\"$ifname\"}[2m]))",
     "legendFormat": "{{ nac }}"
    }
   ]
  }
 ]
}