apiVersion: v1
kind: Secret
metadata:
    name: chargeflux-env
    namespace: chargeflux
data:
    CHARGEFLUX_URL: ENC[AES256_GCM,data:NMQIpiBbAfuCf74YXQI8cyRTnMmmPfep1o119mlHtyl0nhKu,iv:vB6WnbEbxbI1sESRWrdgjaIfwUwFHHp5wFe/ac/hJ+8=,tag:D1S3R4+TrRSWY4rdM0JrYw==,type:str]
    CHARGEFLUX_INFLUXDB_ORG: ENC[AES256_GCM,data:hkksOZa3cAJ0QZEEXTQvmQ==,iv:8zhQhvAlIlvbRBt6TK26m2Nn8AMzNelqQ+0Wd7Nyfa8=,tag:/KW6kE8K4EiDbDiNxx5iAQ==,type:str]
    CHARGEFLUX_INFLUXDB_BUCKET: ENC[AES256_GCM,data:L1VvQe7kvJSV1LZv,iv:zzT7E7I7zsdqTOhqwHQVjmVmgjkquCZ1/eYMkv8oi8I=,tag:XMJ9DrSOwkjZC3RRiNbuVw==,type:str]
    CHARGEFLUX_INFLUXDB_TOKEN: ENC[AES256_GCM,data:YrNipixW7c+OMkaR9Oany4RlpWAThul2DcxzlLbgiqe3V6eirO9BL633ob727p7Vu5kyyhUZ5c//WNDObjIcrkZiN3MqKUGhQQmy8MXxsxHs99UaRi+ivF+zdxdV4deT5AXQ2Jc480NoLOsqI8Hbl+NrZbxQDyW8,iv:5orfHUIM9eW1xt8G4rclDIemG4Hikmv7QvvHgzP3BLc=,tag:tnFHKNTQhThtzWvq6LCWdQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    lastmodified: '2023-11-15T15:48:51Z'
    mac: ENC[AES256_GCM,data:dDeQJCVdj89eBPnni7D61DM/YxXgtQ34KkewdRi/T5qjHimkSG2rkCIcZFFP/g3W28O4ma7aRq0P8AcXjT+t2xqoJx3RHhqyTl4vFslZsyqezjpbPmIj906eiFGRdZ6j+wWExS1YSto+u+CN+Im6aJCxsBS49qih7uhBm4vNa2I=,iv:9iuSgd6xtJ/0UP2KlfCH3HwXaRlHuReg9brVDAjuuGY=,tag:CwUwTtF7VT8MsK+phsEKOg==,type:str]
    pgp:
    -   created_at: '2023-11-15T15:48:50Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA59YQxrIsWI6AQ//fwig1Ve6me4V4H4aWsQQjN8/VJV4aFPyx4Ql9VhY7LOc
            nacJDBNrbN8PfOJdriTSI5G8lfNn6UFYUEUiKtwWrtyGPybgg/qLZ6wF5HausNgI
            ICUsu2o6jVn/Du2W4MPgGlydK7pfDg+8rkBcbzdgxeE6PCtqejsG6EdhKS2RRNLh
            MqA+nzZRnw5uy1YB8hHbZIcWxD7jVIvDnytcemi9pUVV2AYok9cv/gFBCB801mOk
            bwDi47bcspdeeaEoNhzZB8RhksvkRNIMqHX6Q/3KGMp31rfXDfh/1hJeUtmjh36e
            9QwifcIgSyjBzjjG6wNokwy2Twj1SHIrk4UFOhqiqG9rxCM2x/jmoFMSJt+X+aM1
            rLvNVbqbGOLLDxrmiuVn1655jFY1hNzFQGPO0wYSh0/00XbhffmHHkTdU1c1e+Gu
            75zPWRhIZ8xg6s6ehvW9WNvv7PhQQVpwQODSaHd/MeN8f0oLrciDfUKfLxo/qXm6
            A5hvTvHjkRV2Xc+CMPzbk6StfY75L/fqcIB7BL/mxq1oBRUGrrlkhsuDvbf56viz
            LVo6QrW7lIcMwm4s3Ym+h9MDS1NkpWrVwB7OQA/86f68VSrolA8/G9HI2ZYvu2tn
            xWWMWlLf5tmR9wunyqy+5KtnLwNfJCPzghBsoeZkCEBTKVQnzyl3Q4CK+IpocJDS
            XAGr5w1pa/7et6krEvhjbmxIHNDqXoMTnibjM4sAKxRF03gvcEqVLd157W8Iy51d
            aTd9N3Fz31R82yPth+EW6S7aw/I/hsiJOsU+MZ975W2Djc+7xGMTCF3nHb3l
            =S3ac
            -----END PGP MESSAGE-----
        fp: 4D72B62BB844B05E12DEC3A9A3AEC49250A67E2A
    encrypted_regex: ^(data|stringData)$
    version: 3.6.1
