apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pdns-admin
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
  labels:
    app.kubernetes.io/name: pdns-admin
    app.kubernetes.io/instance: pdns-admin-efgh
  namespace: pdns-admin
spec:
  tls:
  - hosts:
    - pda.9ka.nl
    secretName: pdns-admin
  ingressClassName: nginx
  rules:
  - host: pda.9ka.nl
    http:
      paths:
      - backend:
          service:
            name: pdns-admin
            port:
              name: http
        path: /
        pathType: ImplementationSpecific
