apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pda-data
  labels:
    app.kubernetes.io/name: pdns-admin
    app.kubernetes.io/instance: pdns-admin-efgh
spec:
  storageClassName: nfs-nvme
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 256Mi
