apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      chart: kube-prometheus-stack
      version: 32.2.0
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
  values:
    fullnameOverride: kps
    defaultRules:
      create: false
    alertmanager:
      enabled: false
    coreDns:
      enabled: false
    kubeApiServer:
      enabled: false
    kubelet:
      enabled: true
    kubeControllerManager:
      enabled: false
    kubeDns:
      enabled: false
    kubeEtcd:
      enabled: false
    kubeScheduler:
      enabled: false
    kubeProxy:
      enabled: false
    kube-state-metrics:
      resources:
        requests:
          cpu: 50m
          memory: 24Mi
        limits:
          cpu: 250m
          memory: 128Mi
      prometheus:
        monitor:
          relabelings:
          - sourceLabels:
            - "__meta_kubernetes_pod_node_name"
            targetLabel: node_name
    grafana:
      persistence:
        enabled: true
        size: 1Gi
      admin:
        existingSecret: grafana-admin-user
      defaultDashboardsEnabled: false
      envFromSecret: grafana-env-vars
      extraSecretMounts:
      - name: auth-generic-oauth-secret-mount
        secretName: grafana-generic-oauth
        defaultMode: 0440
        mountPath: /etc/secrets/auth_generic_oauth
        readOnly: true
      serviceMonitor:
        enabled:
          false
      grafana.ini:
        server:
          root_url: https://grafana.9ka.nl
        paths:
          data: /var/lib/grafana/data
          logs: /var/log/grafana
          plugins: /var/lib/grafana/plugins
          provisioning: /etc/grafana/provisioning
        analytics:
          check_for_updates: false
        log:
          mode: console
        grafana_net:
          url: https://grafana.net
        auth.generic_oauth:
          enabled: true
          name: 9ka
          allow_sign_up: true
          client_id: $__file{/etc/secrets/auth_generic_oauth/client_id}
          client_secret: $__file{/etc/secrets/auth_generic_oauth/client_secret}
          scopes: openid profile email
          auth_url: https://dex.9ka.nl/auth
          token_url: https://dex.9ka.nl/token
          api_url: https://dex.9ka.nl/userinfo
        users:
          allow_org_create: false
          auto_assign_org: true
          auto_assign_org_role: Admin
        security:
          allow_embedding: true
      ingress:
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt
        enabled: true
        ingressClassName: nginx
        hosts:
        - grafana.9ka.nl
        tls:
        - secretName: grafana-tls
          hosts:
          - grafana.9ka.nl
      plugins:
      - fetzerch-sunandmoon-datasource
      sidecar:
        datasources:
          searchNamespace: ALL
        dashboards:
          searchNamespace: ALL
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            cpu: 100m
            memory: 96Mi
      resources:
        requests: 
          cpu: 150m
          memory: 100Mi
        limits:
          cpu: 1
          memory: 200Mi
    prometheus:
      enabled: false
    prometheusOperator:
      resources:
        limits:
          cpu: 500m
          memory: 256Mi
        requests:
          cpu: 100m
          memory: 128Mi
    prometheus-node-exporter:
      hostNetwork: false
      extraArgs:
      - --collector.filesystem.ignored-mount-points=^/(dev|proc|sys|var/lib/docker/.+|/run/containerd/.+)($|/)
      - --collector.filesystem.ignored-fs-types=^(autofs|binfmt_misc|cgroup|configfs|debugfs|devpts|devtmpfs|fusectl|hugetlbfs|mqueue|overlay|proc|procfs|pstore|rpc_pipefs|securityfs|sysfs|tracefs|tmpfs)$
      - --collector.mountstats
      prometheus:
        monitor:
          relabelings:
          - sourceLabels:
            - "__meta_kubernetes_pod_node_name"
            targetLabel: node_name
      resources:
        requests:
          cpu: 50m
          memory: 20Mi
        limits:
          cpu: 400m
          memory: 50Mi
