apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
spec:
  interval: 5m
  chartRef:
    kind: OCIRepository
    name: kube-prometheus-stack
  values:
    fullnameOverride: kps
    defaultRules:
      create: false
    alertmanager:
      enabled: false
    coreDns:
      enabled: false
    kubeApiServer:
      enabled: false
    kubelet:
      enabled: true
    kubeControllerManager:
      enabled: false
    kubeDns:
      enabled: false
    kubeEtcd:
      enabled: false
    kubeScheduler:
      enabled: false
    kubeProxy:
      enabled: false
    kube-state-metrics:
      resources:
        requests:
          cpu: 50m
          memory: 24Mi
        limits:
          cpu: 250m
          memory: 196Mi
      prometheus:
        monitor:
          relabelings:
          - sourceLabels:
            - "__meta_kubernetes_pod_node_name"
            targetLabel: node_name
    grafana:
      deploymentStrategy:
        type: Recreate
      persistence:
        enabled: true
        size: 1Gi
        storageClassName: proxmox-zfs-nvme
      admin:
        existingSecret: grafana-admin-user
      defaultDashboardsEnabled: false
      envFromSecret: grafana-env-vars
      serviceMonitor:
        enabled:
          false
      grafana.ini:
        server:
          root_url: https://grafana.9ka.nl
        paths:
          data: /var/lib/grafana/data
          logs: /var/log/grafana
          plugins: /var/lib/grafana/plugins
          provisioning: /etc/grafana/provisioning
        analytics:
          check_for_updates: false
        log:
          mode: console
        grafana_net:
          url: https://grafana.net
        security:
          allow_embedding: true
        auth.jwt:
          enabled: true
          header_name: cf-access-jwt-assertion
          username_claim: email
          email_claim: email
          auto_sign_up: true
          jwk_set_url: https://efgh.cloudflareaccess.com/cdn-cgi/access/certs
          expect_claims: '{"iss": "https://efgh.cloudflareaccess.com"}'
        users:
          auto_assign_org: true
          auto_assign_org_role: Admin
      ingress:
        annotations:
          external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
          external-dns.alpha.kubernetes.io/hostname: grafana.9ka.nl
          external-dns.alpha.kubernetes.io/target: 431113a6-4cf3-4a66-9750-17113ae2e689.cfargotunnel.com
        enabled: true
        ingressClassName: cilium
        hosts:
        - grafana.9ka.nl
      plugins:
      - fetzerch-sunandmoon-datasource
      - gapit-htmlgraphics-panel
      - pr0ps-trackmap-panel
      - natel-plotly-panel
      sidecar:
        datasources:
          searchNamespace: ALL
        dashboards:
          searchNamespace: ALL
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            cpu: 100m
            memory: 128Mi
      rbac:
        pspEnabled: false
      resources:
        requests: 
          cpu: 150m
          memory: 100Mi
        limits:
          cpu: 1
          memory: 200Mi
    prometheus:
      enabled: false
    prometheusOperator:
      resources:
        limits:
          cpu: 500m
          memory: 256Mi
        requests:
          cpu: 100m
          memory: 128Mi
    prometheus-node-exporter:
      hostNetwork: false
      extraArgs:
      - --collector.filesystem.ignored-mount-points=^/(dev|proc|sys|var/lib/docker/.+|/run/containerd/.+)($|/)
      - --collector.filesystem.ignored-fs-types=^(autofs|binfmt_misc|cgroup|configfs|debugfs|devpts|devtmpfs|fusectl|hugetlbfs|mqueue|overlay|proc|procfs|pstore|rpc_pipefs|securityfs|sysfs|tracefs|tmpfs)$
      - --collector.mountstats
      prometheus:
        monitor:
          relabelings:
          - sourceLabels:
            - "__meta_kubernetes_pod_node_name"
            targetLabel: node_name
      resources:
        requests:
          cpu: 50m
          memory: 20Mi
        limits:
          cpu: 400m
          memory: 50Mi
