apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cnpg
spec:
  interval: 5m
  chart:
    spec:
      chart: cloudnative-pg
      version: 0.26.1
      sourceRef:
        kind: HelmRepository
        name: cnpg