apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cnpg
spec:
  interval: 5m
  chart:
    spec:
      chart: cloudnative-pg
      version: 0.27.1
      sourceRef:
        kind: HelmRepository
        name: cnpg
  values:
    resources:
      requests:
        memory: 50Mi
        cpu: 5m
      limits:
        memory: 200Mi
        cpu: 250m